### ISSUE TITLE
no available gradle version

### ISSUE THREAD

**Issue by carbon1985** [lingochamp/okdownload#1]
没有可用的gradle版本，看来这个repository是新创建的，请问作者计划什么时候发布一个release呢？

**Comment by Jacksgong** [comment]
@carbon1985 恩，多谢关注，由于这个库作为FileDownloader2的全新版本，我们最晚会在元旦前发布第一个版本。

**Comment by mitty1987** [comment]
元旦过了哇...

**Comment by Jacksgong** [comment]
@mitty1987 十分的抱歉。。。最近公司内部事务较多，我会在保证质量的情况下，尽可能挤时间完善第一个版本上线。
