### ISSUE TITLE
当任务开始时，获取到块的下载速度异常大

### ISSUE THREAD

**Issue by MooeKayo** [lingochamp/okdownload#10]
文件大小：1MB
![qq 20180214171233](https://user-images.githubusercontent.com/28668856/36196092-8e52bcee-11aa-11e8-8f12-e30fd67cc5d5.png)

文件大小：50MB
![qq 20180214171802](https://user-images.githubusercontent.com/28668856/36196260-1f1ad612-11ab-11e8-9db8-1ca8b6622b3e.png)

下载开始一段时间后就不会出现这种情况

**Comment by Jacksgong** [comment]
块速度是计算的真实值，并非BUG。

**Comment by Wangct23** [comment]
1.0.1修复了吗？我用1.0.1下载局域网视频的时候很容易卡死呀。
