### ISSUE TITLE
Android 8.0版本 对静态注册的广播作了限制，当下载成功后，收不到广播，有计划增加替代方案。

### ISSUE THREAD

**Issue by Leovy** [lingochamp/okdownload#100]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
广播的问题跟 OkDownload 没有关系吧。
