### ISSUE TITLE
是否可以修改生成ID规则？

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#103]
想问下，可以自动生成ID么？我看现在下载全是1，2这样的，下完了，再重新下还是1，2，这样有可能会重，我可以把生成ID的规则改一下么？

**Comment by rantianhua** [comment]
OkDownload 不再开发自定义 id 的接口，因为自定义 id 其实容易出现问题，还是有下载库自己维护更好。你看到的 1, 2 这样的对你不会有什么影响的，也不用担心会重复，对于 OkDownload 来说，这个 id 是全局维护的，会保证同一时刻不会出现重复的 id 。
