### ISSUE TITLE
StatusUtil.getStatus方法BUG?

### ISSUE THREAD

**Issue by long729789688** [lingochamp/okdownload#104]
### OkDownload Version

v1.0.3

### Problem Describe

我用下面这个方法返回来的状态是不正确的，我下载url都不一样，只是保存路径和文件名一样，都给我返回的是COMPLETED的状态
StatusUtil.Status status = StatusUtil.getStatus(url, dir.getPath(), filename);

**Comment by hywenbinger** [comment]
从源码看，是按文件路径和名字获取的任务状态，所以会出现上面的bug。
是不是应该再拿url，文件路径等去数据库查一下？

**Comment by rantianhua** [comment]
其实也不能说是 bug ，是目前的策略使然。这个问题在 #38 有讨论过，你可以看一下，另外如果你有 好的建议，欢迎提出来。之后我们持续在 #38 上面讨论。
