### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by codingBobo** [lingochamp/okdownload#108]
### OkDownload Version

v1.0.3

### Problem Describe

download error,  i get this callback as below

### Log

    currentOffset:1382969--totalLength:2066371
06-27 20:17:17.486 31790-31790: currentOffset:1604153--totalLength:2066371
06-27 20:17:17.500 31790-31790: currentOffset:1653097--totalLength:2066371
06-27 20:17:21.254 31790-31790: currentOffset:1657193--totalLength:2066371
06-27 20:17:21.779 31790-31790: currentOffset:1755285--totalLength:2066371
06-27 20:17:22.086 31790-31790: currentOffset:1935509--totalLength:2066371
06-27 20:17:24.049 31790-31790: currentOffset:2001045--totalLength:2066371
06-27 20:17:24.343 31790-31790: currentOffset:2066371--totalLength:2066371
06-27 20:17:24.366 31790-31790: error:java.io.IOException: The current offset on block-info isn't update correct, 0 != 413274 on 1

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
该问题 v1.0.4 版本已经修复 #129 ，目前最新是 v1.0.5 ，你可以升级一下。
