### ISSUE TITLE
下载mp4文件完成后，播放出错

### ISSUE THREAD

**Issue by Wangct23** [lingochamp/okdownload#109]
v1.0.3 
今天在下载mp4时，发现下载的文件概率性播放出错。用exoplayer2 或者macbook IINA播放器都会出错。
重新下载后，播放OK。
没有抓到重要信息，请问这种情况大概会是什么原因，可以给个方向帮忙定位吗？
谢谢

**Comment by Ernest-su** [comment]
把播放失败的mp4文件md5和播放OK的文件md5对比一下是否一致。

**Comment by wensefu** [comment]
遇到同样的问题。改用系统DownloadManager ok.
貌似在弱网环境下高概率出现。

**Comment by rantianhua** [comment]
1.0.3 版本在写入流的逻辑弱网下确认有点儿问题，已经修复，现在最新版本 v1.0.5 ，可以升级看看。
