### ISSUE TITLE
DownloadDispatcher

### ISSUE THREAD

**Issue by Wangct23** [lingochamp/okdownload#111]
v1.0.3
在DownloadDispatcher.java中，下面的方法在执行结束之前为什么要return呢？
![image](https://user-images.githubusercontent.com/17804057/42252006-21b0e206-7f6d-11e8-9194-a7bb8a647458.png)

**Comment by Jacksgong** [comment]
这个是为了避免没必要的操作，这里其实是有所耦合("内聚")`DownloadDispatcher`其他方法的逻辑的的。

原因是: 一个`task`只有可能在一个队列中，要不是 `readyAsyncCalls`，要不是`runningAsyncCalls`，要不是`runningSyncCalls`，并且在整个`DownloadDispatcher`中的所有队列中，有且只有一份。

因此只要在任意一个队列中找到，就没有必要在其他队列找了。
