### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by ChinhQT** [lingochamp/okdownload#114]
I have some error, when downloading a song. This is the link to download ( https://aredir.nixcdn.com/NhacCuaTui848/LkDonXuanNayNhoXuanXuaCauChuyenDauNam-DuongHongLoanLeSang-2921239.mp3?st=L36v_QlDP6rwBtx9BK6HFQ&e=1530812739&download=true) . And the error is 

07-05 01:00:41.023 13120-13470/com.liulishuo.okdownload.sample D/DownloadCache: catch unknown error java.net.ProtocolException: Unexpected status line: D3��������=TALB����������nhaccuatui.com��TIT2������A����Lk Đón Xuân Này Nhớ Xuân Xưa, Câu Chuyện Đầu Năm��TPE1����������Dương Hồng Loan, Lê Sang��TCON����������Trữ Tình��TSSE����������Lavf55.0.100����������������������������������������������������������������������Info����������6���Y����
07-05 01:00:41.025 13120-13478/com.liulishuo.okdownload.sample D/DownloadChain: release connection com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection@fd1675b task[1] block[0]
07-05 01:00:44.382 13120-13471/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish connection task(1) block(1) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], connection=[keep-alive], content-disposition=[attachment;], content-length=[1959098], content-range=[bytes 1959100-3918197/5877296], content-type=[audio/mpeg], date=[Wed, 04 Jul 2018 18:00:43 GMT], etag=["52cb845a-59ae30"], last-modified=[Tue, 07 Jan 2014 04:36:42 GMT], server=[nginx], x-proxy-cache=[HIT]}
07-05 01:00:44.384 13120-13472/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish connection task(1) block(2) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], connection=[keep-alive], content-disposition=[attachment;], content-length=[1959098], content-range=[bytes 3918198-5877295/5877296], content-type=[audio/mpeg], date=[Wed, 04 Jul 2018 18:00:43 GMT], etag=["52cb845a-59ae30"], last-modified=[Tue, 07 Jan 2014 04:36:42 GMT], server=[nginx], x-proxy-cache=[HIT]}
07-05 01:00:44.395 13120-13463/com.liulishuo.okdownload.sample D/CallbackDispatcher: taskEnd: 1 ERROR java.net.ProtocolException: Unexpected status line: D3��������=TALB����������nhaccuatui.com��TIT2������A����Lk Đón Xuân Này Nhớ Xuân Xưa, Câu Chuyện Đầu Năm��TPE1����������Dương Hồng Loan, Lê Sang��TCON����������Trữ Tình��TSSE����������Lavf55.0.100����������������������������������������������������������������������Info����������6���Y����
07-05 01:00:44.395 13120-13463/com.liulishuo.okdownload.sample D/NotificationActivity: taskEnd ERROR java.net.ProtocolException: Unexpected status line: D3��������=TALB����������nhaccuatui.com��TIT2������A����Lk Đón Xuân Này Nhớ Xuân Xưa, Câu Chuyện Đầu Năm��TPE1����������Dương Hồng Loan, Lê Sang��TCON����������Trữ Tình��TSSE����������Lavf55.0.100����������������������������������������������������������������������Info����������6���Y����
07-05 01:00:44.396 13120-13163/com.liulishuo.okdownload.sample D/RemitSyncExecutor: remove free bunch id 1
07-05 01:00:44.396 13120-13463/com.liulishuo.okdownload.sample D/DownloadCall: call is finished 1

**Comment by rantianhua** [comment]
Please refer to https://github.com/square/okhttp/issues/3662.
