### ISSUE TITLE
只支持http协议吗

### ISSUE THREAD

**Issue by xiaoyaomimi** [lingochamp/okdownload#115]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
默认使用 `URLConnectyion`，也支持传入`OkHttp`，因此默认只支持 `http`与`https`协议，其他协议支持可以自行参考项目中的`okhttp` module，实现 `DownloadConnection` 然后参考[文档](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component)传入即可。
