### ISSUE TITLE
有断点续传的开关吗？不想使用断点续传怎么办

### ISSUE THREAD

**Issue by JHwangxiaotian** [lingochamp/okdownload#116]
下载数据的时候，部分接口不支持断点续传，使用OKDownload的时候，默认是开启断点续传的，我之前的做法是，检查到暂停或者错误的时候直接remove(id),每次需要根据DowmloadTask来获取id，然后才能remove。有没有方法在task创建的时间就禁掉断点续传的功能啊！

**Comment by YellowPlusX** [comment]
继承DownloadUriOutputStream.Factory，然后重写supportSeek方法并返回false

**Comment by YellowPlusX** [comment]
继承DownloadUriOutputStream.Factory重写supportSeek方法并返回false
