### ISSUE TITLE
404 异常

### ISSUE THREAD

**Issue by ITRocker** [lingochamp/okdownload#118]
### OkDownload Version

v1.0.3

 cause = [ERROR], realCause = [Response code can't handled on internal 404 with current offset 0],
这个404一般是什么原因产生的，测试服务器和正式服务器端代码一模一样，测试服务器可以下载，正式服务器报错，返回404异常

**Comment by Jacksgong** [comment]
建议根据[文档](https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload)打开日志，然后在日志中，查看具体的请求与响应来确认你的404问题。

**Comment by ITRocker** [comment]
问题解决了

**Comment by YuanTiger** [comment]
您好，请问是您如何解决404的问题的？

我这边也遇到了404的问题，网页上直接打开链接是可以进行下载并成功的。
