### ISSUE TITLE
下载404 不存在地址 空指针崩溃  

### ISSUE THREAD

**Issue by HiloFeng** [lingochamp/okdownload#119]
### OkDownload Version
v1.0.3
Listener4SpeedAssistExtend  
方法     speedModel.taskSpeed   中 taskSpeed 对象为空 
    @Override
    public boolean dispatchTaskEnd(DownloadTask task, EndCause cause, @Nullable Exception realCause,
                                   @NonNull Listener4Assist.Listener4Model model) {
        final Listener4SpeedModel speedModel = (Listener4SpeedModel) model;
        speedModel.taskSpeed.endTask();

        if (callback != null) {
            callback.taskEnd(task, cause, realCause, speedModel.taskSpeed);
        }

        return true;
    }

**Comment by rantianhua** [comment]
Duplicated with #121 .
