### ISSUE TITLE
5.0以下版本下载报错，高版本可以正常下载

### ISSUE THREAD

**Issue by heyyue** [lingochamp/okdownload#12]
Could not find method android.system.Os.ftruncate, referenced from method com.liulishuo.okdownload.core.file.DownloadUriOutputStream.setLength

**Comment by Jacksgong** [comment]
多谢反馈。

**Comment by Jacksgong** [comment]
可否告知下这报的具体是什么`Exception`，是`VerifyError`吗?

**Comment by Jacksgong** [comment]
已经修复，你可以在最新的1.0.0-SNAPSHOT上面验证；由于无法像`RandomAccessFile`一样直接访问`Libcore`包，因此`5.0`以下不会做下载前的空间预分配，不过不会影响5.0以下的`okdownload`正常使用。
