### ISSUE TITLE
只是想后台下载，查看的时候才监听进度

### ISSUE THREAD

**Issue by jiechic** [lingochamp/okdownload#126]
发现发起下载，一定要有监听进度的对象？
不能先发起下载，后台在下载中，然后打开某个页面的时候，然后找到task，去添加进度监控吗？

**Comment by Jacksgong** [comment]
正常来说，如果你不需要监听可以传入一个空实现的监听的，或者是空的监听，在接下来的`1.0.4`的版本也已经支持了`DownloadTask#replaceListener`的方法。

**Comment by jiechic** [comment]
试过传入null监听，提示null exception，传入空实现监听，这代码不优雅。

**Comment by rantianhua** [comment]
下一版可以利用 kotlin channel 实现这个功能，敬请期待
