### ISSUE TITLE
The current offset on block-info isn't update correct, 5110 != 4167688 on 1

### ISSUE THREAD

**Issue by HiloFeng** [lingochamp/okdownload#132]
### OkDownload Version

v1.0.4

偶现 The current offset on block-info isn't update correct, 5110 != 4167688 on 1 此异常

**Comment by coderlzx** [comment]
+1，都完整下载好了，但还是报这个错

**Comment by sadlongit** [comment]
+1

**Comment by ITRocker** [comment]
+1

**Comment by zhoufengAndroid** [comment]
+1

**Comment by blueskky** [comment]
.+1

**Comment by rantianhua** [comment]
抱歉这么晚回复。该问题已经在 v1.0.5 修复了，对应的 Issue 为 #129 ，在 v1.0.5 的 Changelog 也可以看到记录，请各位升级即可。
