### ISSUE TITLE
关于设置超时(timeout)时间的问题

### ISSUE THREAD

**Issue by z1zong** [lingochamp/okdownload#133]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe
遇到了一个情景：
由于下载连接的不稳定，会经常timeout 然后taskEnd。
1. 尝试用advanced用法文档里面的方法（Injection Component）没有成功。
    使用OkDownload.Builder时候，只设置了connectionFactory，然后出现了无法下载和连接的问题。
    是否要将所有参数都设置一遍？
    ```java
      DownloadUrlConnection.Factory factory = new DownloadUrlConnection.Factory(
                    new DownloadUrlConnection.Configuration()
                            .connectTimeout(10000)
                            .readTimeout(10000));
            OkDownload.Builder builder = new OkDownload.Builder(this)
                    .connectionFactory(factory);
            OkDownload.setSingletonInstance(builder.build());
    
    // 返回错误信息：Response code can't handled on internal 302 with current offset 0

2. 除去设置connectionFactory外，有没有可以设置连接超时时间的接口？
感谢！

**Comment by kerneltea** [comment]
要是用OkHttp的话,可以在interceptor里设吧。

**Comment by z1zong** [comment]
@kerneltea 
可不可以稍微具体一点呢？可能我研究的不是很清楚，我看到：
okhttpclient是封装在DownloadOkHttp3Connection.class下的，如果要设置Downloader的话要去DownloadUrlConnection.class下的Configuration。
感谢！

**Comment by kerneltea** [comment]
在生成OkHttpClient之前你可以设计超时时间的呀，如果想要自定义处理超时，你可以自定义hook一个interceptor..在interceptor中你可以拦截请求和回复，在这里做延时。

**Comment by Jacksgong** [comment]
嗯，你参照wiki设置方法是正确的，不过改方法传入的是 `DownloadUrlConnection`，并非okhttp3，如果你要使用okhttp3，请直接通过类似的方法设置`DownloadOkHttp3Connection`然后使用相同的方法传入即可。

---

`Response code can't handle on internal 302 with current offset 0` 这个是另外的问题（我猜测是因为你改用了`DownloadUrlConnection`后的问题，这边我看了代码，这里在做校验的时候确实是没有对302进行处理，这个问题后续我们会跟进。

**Comment by owenxiao-AS** [comment]
> ### OkDownload Version
> v1.0.2-SNAPSHOT
> 
> ### Problem Describe
> 遇到了一个情景：
> 由于下载连接的不稳定，会经常timeout 然后taskEnd。
> 
> 1. 尝试用advanced用法文档里面的方法（Injection Component）没有成功。
>    使用OkDownload.Builder时候，只设置了connectionFactory，然后出现了无法下载和连接的问题。
>    是否要将所有参数都设置一遍？
>    ```java
>      DownloadUrlConnection.Factory factory = new DownloadUrlConnection.Factory(
>                    new DownloadUrlConnection.Configuration()
>                            .connectTimeout(10000)
>                            .readTimeout(10000));
>            OkDownload.Builder builder = new OkDownload.Builder(this)
>                    .connectionFactory(factory);
>            OkDownload.setSingletonInstance(builder.build());
>    
>    // 返回错误信息：Response code can't handled on internal 302 with current offset 0
>    ```
> 2. 除去设置connectionFactory外，有没有可以设置连接超时时间的接口？
>    感谢！

这个文档在哪看啊   找了半天么看到
