### ISSUE TITLE
改进版本啦

### ISSUE THREAD

**Issue by 10045125** [lingochamp/okdownload#134]
提几个建议哈：
1.  对于下载器，下载效率是比较重要的一个因素，我阅读了源码，各处的职责非常清晰，扩展性很好。
2. 对于下载器2个必要的功能是多线程（亦或是动态设置线程）、读写分离（只用一个线程来调度IO）
3. 期待一起加入该版本的功能开发，哈哈

**Comment by rantianhua** [comment]
第一点我理解不是建议。第二点 OkDownload 的是有的。第三点欢迎！
