### ISSUE TITLE
使用 Queue 方式下载的时，怎么获取总任务的下载进度？

### ISSUE THREAD

**Issue by iiShadow** [lingochamp/okdownload#136]
### OkDownload Version

v1.0.3

### Problem Describe

 - 只看到有队列中某个任务的下载进度，并没有总任务的下载进度，请问有什么好的方式吗？
- 发现 DownloadContextListener#queueEnd() 的回调，在 context.stop() 的时候也会触发回调？

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
#### 只看到有队列中某个任务的下载进度，并没有总任务的下载进度，请问有什么好的方式吗？

- 你可以通过 `DownloadContextListener#taskEnd` 获知以任务为颗粒度的进度。
- 我们无法获知整体的精确到`byte`的进度，是因为我们无法获知所有任务所要下载的内容大小，除非在开始队列下载的时候，就对所有的任务发起请求等待从所有任务的每个一个响应头中都回去到其大小了再开始逐个下载，这显然是存在问题的
- 你们可以通过单独的API来获得所有任务的大小，在启动队列的时候传入自己的`DownloadListener`监听器，然后再根据`DownloadListener`的回调以及你与你后端协定好的单独API回调的总大小，来获取进度

#### 发现 DownloadContextListener#queueEnd() 的回调，在 context.stop() 的时候也会触发回调？

是的，这只是意味着队列结束，并不是意味着下载完成。相关代码参看 `DownloadContext`源码即可。
