### ISSUE TITLE
通过new DownloadTask.Builder(url, path,filename)方法得到的task是单例的吗

### ISSUE THREAD

**Issue by JHwangxiaotian** [lingochamp/okdownload#138]
我有2个Activity里面都在用DwonloadTask下载任务(两个任务不同)， 当A通过startActivity打开B之后，B开始下载文件， A执行finish，这个时候A会执行if (task != null) task.cancel();   然后B正在下载的任务直接被取消了。PS：因为后台没有使用断点，也没按照标准规范写header所以我在任务错误或者取消的时候都通过id取消任务的
int id = OkDownload.with().breakpointStore().findOrCreateId(task);
OkDownload.with().breakpointStore().remove(id);

是不是因为B在下载的时候 A取消时 直接把B下载的id给取消了？ 那是不是A拿到的task和B拿到的task是同一个对象啊

**Comment by imcloud** [comment]
对象不是，但参数相同生成的id相同
