### ISSUE TITLE
断点非实时

### ISSUE THREAD

**Issue by wheat7** [lingochamp/okdownload#142]
在存断点处打了log发现断点不是在下载时实时存储，by the way，作者是否可以解析一下源码，谢谢～

**Comment by rantianhua** [comment]
断点进度自然不可能下载时实时存储，会有特定的策略保证断点的准确。

**Comment by wheat7** [comment]
不可能的原因能否分享一下？我这里发现的原因是写入数据(数据库或文件)时IO、事务阻塞线程。另外，断点其实可以直接从文件读，每个block下载完成后再合并，这样也不用一开始就占用完整文件大小的空间，这个方案是否有考虑过？

**Comment by rantianhua** [comment]
我理解，你所说的实时的意思是，每当从网络流读取了数据之后，就记录当前 block 下载的进度。其实我说不可能这个词应该换成没必要更加准确。在我们选择的方案里，是通过数据库记录断点信息。在实际进行下载时，没毫秒阶段就有数据读取，按照你说的实时，要在毫秒级进行数据库写操作，对数据来说是一种压力，而且这种压力没什么意义。我们断点的目的是为了记录停止下载时，当前 block 下载的进度，所以我只要保证这一点正确就好了，没有必要跟读取网络流的操作进行同频。

至于你另外一个问题：为什么不用文件作为断点信息，这个我们真的要回忆一下了😂
