### ISSUE TITLE
已下载的文件，再次创建task，task.fileName是null

### ISSUE THREAD

**Issue by kolyneh** [lingochamp/okdownload#147]
### OkDownload Version

v1.0.4

### Problem Describe

已经下载好的文件，再次创建相同链接的task去下载，
这时候 StatusUtil.isCompleted(task) 返回true , 文件名 task.fileName 是空的。

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
StatusUtil.isCompleted(task) file:null fileName:null task:com.liulishuo.okdownload.DownloadTask@c13816c9@1
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
正常，如果你创建的时候没有设置 filename ，而且这个已经是下载过的文件所以不会再发生下载过程，filename 就不会赋值。
