### ISSUE TITLE
Downloading from fragment causes error 

### ISSUE THREAD

**Issue by pravinyo** [lingochamp/okdownload#149]
### Problem Describe

I have modified the NotificationActivity code and created a package that will handle all the download task. All the download request are sent from the fragment. fragment has list of linearViews and each LinearView has a downlaod button, When I click on the download button it crashes the app and returns NullPointerException for DownloadTask.getId(). I am writing for first time so please forgive me.

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.liulishuo.okdownload.DownloadTask.getId()' on a null object reference
        at com.liulishuo.okdownload.UnifiedListenerManager.attachListener(UnifiedListenerManager.java:86)
        at com.example.android.openresources.fetchAdapter.downloader.NotificationDownloadService$GlobalTaskManager.attachListener(NotificationDownloadService.java:130)
        at com.example.android.openresources.fetchAdapter.downloader.NotificationDownloadService.create(NotificationDownloadService.java:37)
        at com.example.android.openresources.InternetArchiveAdapter.fragment.FragmentMedia$1.onClick(FragmentMedia.java:88)
        at android.view.View.performClick(View.java:5269)
        at android.view.View$PerformClick.run(View.java:21556)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```
```

### NavigationActivity code written as a package 
package com.example.android.openresources.fetchAdapter.downloader;

import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.support.annotation.NonNull;
import android.support.v4.app.NotificationCompat;
import android.view.View;

import com.liulishuo.okdownload.DownloadListener;
import com.liulishuo.okdownload.DownloadTask;
import com.liulishuo.okdownload.StatusUtil;
import com.liulishuo.okdownload.UnifiedListenerManager;

import java.io.File;

public class NotificationDownloadService {

    private NotificationDownloadServiceListener listener;
    private CancelReceiver cancelReceiver;

    private DownloadTask task;
    private Context context;

    public NotificationDownloadService(Context context){
        this.context = context;
    }

    public  void create(){
        // for cancel action on notification.
        IntentFilter filter = new IntentFilter(CancelReceiver.ACTION);
        cancelReceiver = new CancelReceiver(task);
        context.getApplicationContext().registerReceiver(cancelReceiver, filter);

        GlobalTaskManager.getImpl().attachListener(task, listener);
        GlobalTaskManager.getImpl().addAutoRemoveListenersWhenTaskEnd(task.getId());
    }

    public boolean isRunning(){
        if (StatusUtil.isSameTaskPendingOrRunning(task)) {
            return true;
        }

        return false;
    }

    public void destroy(){
        context.getApplicationContext().unregisterReceiver(cancelReceiver);
        listener.releaseTaskEndRunnable();
    }

    public void initAction(View v) {
        if (v.getTag() == null) {
            // need to start
            GlobalTaskManager.getImpl().enqueueTask(task, listener);
            //actionTv.setText(R.string.cancel);
            v.setTag(new Object());
        }
    }

    public void initTask(String URL, File parentFile, String filename) {
        task = new DownloadTask
                .Builder(URL,parentFile)
                .setFilename(filename)
                // if there is the same task has been completed download, just delete it and
                // re-download automatically.
                .setPassIfAlreadyCompleted(false)
                .setMinIntervalMillisCallbackProcess(80)
                // because for the notification we don't need make sure invoke on the ui thread, so
                // just let callback no need callback to the ui thread.
                .setAutoCallbackToUIThread(false)
                .build();
    }

    public void initListener(final View view) {
        listener = new NotificationDownloadServiceListener(context,"hello");
        listener.attachTaskEndRunnable(new Runnable() {
            @Override public void run() {
                //actionTv.setText(R.string.start);
                view.setTag(null);
            }
        });

        final Intent intent = new Intent(CancelReceiver.ACTION);
        final PendingIntent cancelPendingIntent = PendingIntent.getBroadcast(context, 0, intent,
                PendingIntent.FLAG_UPDATE_CURRENT);

        listener.setAction(new NotificationCompat.Action(0, "Cancel", cancelPendingIntent));
        listener.initNotification();
    }

    static class CancelReceiver extends BroadcastReceiver {
        static final String ACTION = "cancelOkdownload";

        private DownloadTask task;

        CancelReceiver(@NonNull DownloadTask task) {
            this.task = task;
        }

        @Override public void onReceive(Context context, Intent intent) {
            this.task.cancel();
        }
    }

    static class GlobalTaskManager {
        private UnifiedListenerManager manager;

        private GlobalTaskManager() {
            manager = new UnifiedListenerManager();
        }

        private static class ClassHolder {
            private static final GlobalTaskManager INSTANCE = new GlobalTaskManager();
        }

        static GlobalTaskManager getImpl() {
            return ClassHolder.INSTANCE;
        }

        void addAutoRemoveListenersWhenTaskEnd(int id) {
            manager.addAutoRemoveListenersWhenTaskEnd(id);
        }

        void attachListener(@NonNull DownloadTask task, @NonNull DownloadListener listener) {
            manager.attachListener(task, listener);
        }

        void enqueueTask(@NonNull DownloadTask task,
                         @NonNull DownloadListener listener) {
            manager.enqueueTaskWithUnifiedListener(task, listener);
        }
    }

}

### I am calling in fragment
private NotificationDownloadService downloadService;

downloadBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String downloadURL = Utility.getBASE_DOWNLOAD_URL()+mIdentifier+"/"+file.getName();

                downloadService = new NotificationDownloadService(view.getContext());
                downloadService.create();
                downloadService.initListener(view);
                downloadService.initTask(downloadURL,getParentFile(),file.getName());
                downloadService.initAction(view);

                Toast.makeText(view.getContext(),downloadURL,Toast.LENGTH_SHORT).show();
            }
        });

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by z1zong** [comment]
You init your task after calling getId. You should init task first, then call task.getId(), otherwise your task is NULL.
Try this (move .create() to the end):
`` downloadService = new NotificationDownloadService(view.getContext());
downloadService.initListener(view);
downloadService.initTask(downloadURL,getParentFile(),file.getName());
downloadService.initAction(view);
downloadService.create();``

**Comment by pravinyo** [comment]
Thank you it worked
