### ISSUE TITLE
当网络不好时，下载中断且没有下载任务的错误回调，也没有见到任何异常的抛出

### ISSUE THREAD

**Issue by heyyue** [lingochamp/okdownload#15]
请核查下，谢谢

**Comment by Jacksgong** [comment]
没有会调，说明还在下载，这段时间应该是在等待超时。

**Comment by liuglgithub** [comment]
有断网后，自动重试的机制吗

**Comment by Jacksgong** [comment]
@liuglgithub 其实之前filedownloader这个一直是一个伪需求，因为网络情况复杂。

现在在okdownload中，如果在下载失败后，用户需要重试重试，直接`taskEnd`回调的地方进行重新启动任务即可（`task.enqueue(listener)`），用于判定重试过了几次可以通过`task.addTag`或者是`task.setTag`来进行记录。

更多新的疑惑或者是其他问题，请直接提新Issue。
