### ISSUE TITLE
最新代码checkout 下来后，gradle 环境无法正常加载

### ISSUE THREAD

**Issue by czy520** [lingochamp/okdownload#151]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
没有提供有用的信息。
