### ISSUE TITLE
文档不全，真心不好用

### ISSUE THREAD

**Issue by hong-tang** [lingochamp/okdownload#153]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by cuihee** [comment]
当前是开发版本，文档肯定跟不上的

作者的上一个版本也挺好用的
https://github.com/lingochamp/FileDownloader/blob/master/README-zh.md

**Comment by chaoshuai** [comment]
能把下载的回调说明下吗

**Comment by Jacksgong** [comment]
@chaoshuai 看Wiki: https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline

---

需要说明的已经在Wiki中说明了，有具体哪里存在问题或者wiki看不明白请具体指出，或者提交PR，谢谢。
