### ISSUE TITLE
队列下载 如何移除task

### ISSUE THREAD

**Issue by zhongwen1** [lingochamp/okdownload#158]
### Problem Describe

1 队列下载 如何移除task 并没有报错

**Comment by IdioticMadman** [comment]
队列下载，应该是自己实现的吧？这个库只是有下载的功能

**Comment by rantianhua** [comment]
@zhongwen1 针对你要移除的 Task 调用 pause 方法即可。
@IdioticMadman 请参考 `FileDownloadSerialQueue` 和 `FileDownloadQueueSet`。

**Comment by rantianhua** [comment]
@IdioticMadman 请参考 https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline 。
@zhongwen1 将你想移除的 Task 调用 `cancel` 方法即可。

**Comment by zhongwen1** [comment]
管理类要自己写是吧。

**Comment by zhongwen1** [comment]
我尝试下你说的建议

**Comment by rantianhua** [comment]
管理属于具体的业务，是需要自己按需实现的。

**Comment by hywenbinger** [comment]
@rantianhua cancel不是暂停吗？调了下发现数据库里的任务还在，再次调开始还会继续下载。

**Comment by gzy13543479929** [comment]
> @rantianhua cancel不是暂停吗？调了下发现数据库里的任务还在，再次调开始还会继续下载。

DownloadContext.Builder builder = MyDownloadContext.toBuilder();
builder.unbind()

**Comment by hywenbinger** [comment]
thanks!
