### ISSUE TITLE
Resume download after app stopped.

### ISSUE THREAD

**Issue by Anton111111** [lingochamp/okdownload#161]
Is has ability to resume download after app stopped and started again?
And how to get list of all tasks? Or i need store all tasks myself?

**Comment by Jacksgong** [comment]
## Is has ability to resume download after app stopped and started again?

OkDownload will resume the breakpoint after tasks are interrupted automatically (except the case of the task only download with the very little process and interrupt, what means if the task only has been downloaded very tiny bytes the process of this one will be discarded)

## how to get list of all tasks

You only need to save task id by yourself, and get its info with [wiki](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline#2-get-breakpointinfo-beyond-listener) said.
