### ISSUE TITLE
求助Ip直连

### ISSUE THREAD

**Issue by ITRocker** [lingochamp/okdownload#164]
请问框架是否支持，https请求，Url host替换为Ip 形式的 ip 直连。
如果支持，应该怎么设置。

**Comment by icezheng** [comment]
最近在学习这个组件，看了下并没有对https有多少支持，建议你根据需求继承DownloadUrlConnection或者okHttpConnection甚至自己实现一个，再设置SSL相关参数就可以了。ip直连同理

**Comment by Jacksgong** [comment]
默认如果是https协议走的是`HttpsURLConnection`，如果引了`com.liulishuo.okdownload:okhttp`，那么https协议默认okhttp就支持。如果想要做定制，自己实现`DownloadConnection`接口(可以类似@icezheng 说的，参考已有的)，然后参考[该方式](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component)传入即可。
