### ISSUE TITLE
download file with ServerCanceledException

### ISSUE THREAD

**Issue by fujiandong1991** [lingochamp/okdownload#189]
I have get an error during download a file from my own server. 

Here is the error info, is anyone know the possible cause?

```
com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 200 with current offset 1115376
```
I have tried to open the same file download url in chrome, and the file can be download successfully.

**Comment by rantianhua** [comment]
This exception is thrown during break point check. If download from breakpoint, the response code should be 206 not 200, so this probably is your server error.

**Comment by fujiandong1991** [comment]
> This exception is thrown during break point check. If download from breakpoint, the response code should be 206 not 200, so this probably is your server error.

Thank you!
