### ISSUE TITLE
clone源码后，使用gradle时build错误

### ISSUE THREAD

**Issue by 1379** [lingochamp/okdownload#190]
我在仓库里clone了最新的代码，因为我想研究下okdownloader的源码，我用android studio打开了这个项目，但是build时发生了错误：
CreateProcess error=2, 系统找不到指定的文件。
Open File
它指向了gradle文件的
allprojects {
    apply plugin: 'okcheck'
    repositories {
        jcenter()
        google()
    }
okcheck部分。
您能给我一些关于研究本项目源代码的建议吗。

**Comment by changjiangblog** [comment]
我是一个对gradle和android 都不太熟悉的新手，正在学习

**Comment by rantianhua** [comment]
请提供详细的错误信息，还有你的 Android Studio 版本。

**Comment by zichenly** [comment]
![tim 20181204173612](https://user-images.githubusercontent.com/19464001/49432876-968d0680-f7eb-11e8-96fc-d2a8e72fadfa.png)
