### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by XiongKe94** [lingochamp/okdownload#192]
我要做一个类似应用商店的App：
1.如何查看下载任务
2.动态删除某个任务
3.后台下载
好像后台下载和查看下载任务是不是需要我自己实现？okdownload只负责下载？

**Comment by DaveLinhun** [comment]
@XiongKe94 最近我也涉及到一个应用商店的应用 也遇到了和你一样的困惑，你问的这些问题有答案了吗
