### ISSUE TITLE
暂停和取消的区分

### ISSUE THREAD

**Issue by luoziguang** [lingochamp/okdownload#21]
你好！

之前用过FileDownloader，这两天研究了一下OkDownload，但是从说明文档和Sample中没有看到Pause和Cancel的明确区分，请问在这个版本中已经不需要明确区分Pause和Cancel了吗？还是有什么我没注意到的？

因为实际使用中，某些需求上还是需要这两者都有的。
感谢！

**Comment by Jacksgong** [comment]
其实在[wiki-QA](https://github.com/lingochamp/okdownload/wiki/QA#taskpause-callback-is-missing)中有提到，这里的`Cancel` 就是之前的 `Pause` ，改为`cancel`的原因，是因为这里实质就是`cancel`，只不过下一次启动的时候，如果扫描到有相关的数据，默认会进行断点续传。

如果下一次启动的时候，不希望被断点续传，可以先通过 `OkDownload.with().breakpointStore().remove(id)`的形式，将其数据从缓存中清除，或者更简单直接将目标文件删除掉，下次启动就不会执行断点续传了。
