### ISSUE TITLE
使用DownloadListener4WithSpeed时怎么获取totalLength

### ISSUE THREAD

**Issue by tienhere** [lingochamp/okdownload#212]
### OkDownload Version

v1.0.5
### Problem Describe

如题，在使用DownloadListener4WithSpeed时process中只有currentOffset，没有totalLength，那么总大小怎么获取呢，例如要显示总大小或显示当前下载%比时都要用到

**Comment by tennkou** [comment]
@Override
            public void infoReady(@NonNull DownloadTask task, @NonNull BreakpointInfo info,
                                  boolean fromBreakpoint,
                                  @NonNull Listener4SpeedAssistExtend.Listener4SpeedModel model) {
                statusTv.setText(R.string.info_ready);
 
 
                totalLength = info.getTotalLength();
                readableTotalLength = Util.humanReadableBytes(totalLength, true);
                DemoUtil.calcProgressToView(progressBar, info.getTotalOffset(), totalLength);
            }

readableTotalLength 应该就是totalLength

--------------------- 
作者：sz_denny 
来源：CSDN 
原文：https://blog.csdn.net/szdenny/article/details/80332993 
版权声明：本文为博主原创文章，转载请附上博文链接！
