### ISSUE TITLE
How to start download in background?

### ISSUE THREAD

**Issue by javierpe** [lingochamp/okdownload#22]

**Comment by Jacksgong** [comment]
- If you want to download in the background, you just use `DownloadTask#enqueue` like [wiki](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline) said, it will run the download task on the background thread.
- If you want a download service running on the separate process, on the current version we don't provide yet, but on the further version we will implement it with `DownloadDispatcher` on `com.liulishuo.okdownload:process` what is like sqlite or okhttp(refs [wiki](https://github.com/lingochamp/okdownload/wiki#import-okdownload-through-gradle))
