### ISSUE TITLE
如何限制批量下载中同时下载的个数

### ISSUE THREAD

**Issue by liuxing917738** [lingochamp/okdownload#220]
如何限制批量下载中同时下载的个数?

现在目前做的demo中批量下载十几个视频,
未下载完成结束的情况下退出APP重新进入就ANR无响应了,

目前的下载是同步进行,比如同时十几个一起下载,

想限制每次只能同时5个下载,需要如何改.
谢谢

**Comment by blisssayyid** [comment]
DownloadDispatcher.setMaxParallelRunningCount(MAX_COUNT)

**Comment by nanfeifei** [comment]
> DownloadDispatcher.setMaxParallelRunningCount(MAX_COUNT)

这个写在哪里，我下载的时候总是几率出现下载中断的问题，你们有吗

**Comment by blisssayyid** [comment]
> > DownloadDispatcher.setMaxParallelRunningCount(MAX_COUNT)
> 
> 这个写在哪里，我下载的时候总是几率出现下载中断的问题，你们有吗

在一开始，调用之下载之前

下载中断，我猜是因为Timeout，我配置了一下没出现了就
