### ISSUE TITLE
1.0.0版本的DownloadContextListener缺少taskEnd回调

### ISSUE THREAD

**Issue by walkthehorizon** [lingochamp/okdownload#23]
如题，clone得到的代码DownloadContextListener和1.0.0release版本的不一致，缺少taskEnd回调，需要独立添加一个DownLoadListener，不够方便，期望更新

**Comment by Jacksgong** [comment]
嗯，对的。在1.0.1-SNAPSHOT上面已经有了，可以参照[wiki](https://github.com/lingochamp/okdownload/wiki) 引入1.0.1-SNAPSHOT。

**Comment by walkthehorizon** [comment]
这速度，**牛B**
