### ISSUE TITLE
下载完成的文件再次获取状态就只能获取到UNKNOWN吗？

### ISSUE THREAD

**Issue by qinxianyuzou** [lingochamp/okdownload#244]
我测试下载，发现当文件下载成功之后，获取到的状态一直都是UNKNOWN而不是完成，而文件未下载的时候也是UNKNOWN，这样我根本没办法判断一个文件到底下载完没有，只能根据自己的标记去处理？还得是做了本地缓存？是不是我的使用方法不对？

**Comment by caiyoufei** [comment]
我这边发现混淆之后获取到的就是UNKNOWN，没有混淆获取到的是对的
@qinxianyuzou

**Comment by caiyoufei** [comment]
@qinxianyuzou 
在lib中配置不行，在app中配置正常判断了

**Comment by qinxianyuzou** [comment]
通过试验，需要正确引入sql包，并且混淆排除，这两点得参考demo源码
