### ISSUE TITLE
 为什么下载任何一个链接地址，原始url被请求了多次？

### ISSUE THREAD

**Issue by blueway** [lingochamp/okdownload#252]
### OkDownload Version

v1.0.5 

### Problem Describe

 为什么下载一个任何链接地址，原始url被请求了多次？

### Log

 

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by liuyouth** [comment]
> ### OkDownload版本
> V1.0.5
> 
> ### 问题描述
> 为什么下载一个任何链接地址，原始URL被请求了多次？
> 
> ### 日志

是多线程下载同一个文件导致的么？

**Comment by jasonzhang1986** [comment]
我来分析下，可能有如下两个原因：
1. 每个下载流程都会先 new 一个 Trial 的 Connection 去获取链接的信息，主要是文件大小，文件类型
2. 在 1 的基础上判断是否分片进行多线程下载

所以一次下载流程至少会访问 2 次链接地址
```Java
DownloadCall.java

// 2. remote check.
final BreakpointRemoteCheck remoteCheck = createRemoteCheck(info);
try {
    //Trial 尝试获取文件的信息，比如文件大小，文件类型等
    remoteCheck.check();
} catch (IOException e) {
    //处理前置条件的异常，在这里会对错误进行分类
    cache.catchException(e);
    break;
}
//设置重定向的地址，如果有重定向的话
cache.setRedirectLocation(task.getRedirectLocation());
```

**Comment by rantianhua** [comment]
@liuyouth 和 @jasonzhang1986 所说完全正确，感谢回答。
