### ISSUE TITLE
java.lang.IllegalStateException: context == null

### ISSUE THREAD

**Issue by AwakenDragon** [lingochamp/okdownload#253]
java.lang.IllegalStateException: context == null
	at com.liulishuo.okdownload.OkDownload.with(OkDownload.java:98)
	at com.liulishuo.okdownload.DownloadTask.<init>(DownloadTask.java:197)
	at com.liulishuo.okdownload.DownloadTask$Builder.build(DownloadTask.java:916)

OkDownloadProvider.context == null 概率被判断为ture

**Comment by Charles199310** [comment]
我也遇上过这个问题，通过反射设置这个context为Application的context就好，我猜测是因为有多个进程调用的缘故

**Comment by qq549631030** [comment]
同样遇到这个问题，Bugly上收集到的都是三星S8、S9 plus Android9.0手机出现这个问题

**Comment by Heber-xu** [comment]
这个问题在多进程中基本都会出现，解决方法很简单，自己写一个OkDownload的单例，代码如下：
OkDownload.setSingletonInstance(new OkDownload.Builder(context.getApplicationContext()).build());
之后调用任务下载：
DownloadTask task = new DownloadTask.Builder(url, new File(parentDir))
                .setFilename(filename)
                // the minimal interval millisecond for callback progress
                .setMinIntervalMillisCallbackProcess(500)
                // do re-download even if the task has already been completed in the past.
                .setPassIfAlreadyCompleted(false)
                .build();
        task.enqueue(listener);

**Comment by liushengqiang** [comment]
> 这个问题在多进程中基本都会出现，解决方法很简单，自己写一个OkDownload的单例，代码如下：
> OkDownload.setSingletonInstance(new OkDownload.Builder(context.getApplicationContext()).build());
> 之后调用任务下载：
> DownloadTask task = new DownloadTask.Builder(url, new File(parentDir))
> .setFilename(filename)
> // the minimal interval millisecond for callback progress
> .setMinIntervalMillisCallbackProcess(500)
> // do re-download even if the task has already been completed in the past.
> .setPassIfAlreadyCompleted(false)
> .build();
> task.enqueue(listener);

您好，能说详细点吗？没看懂你说的OkDownload单例是怎么样的？

**Comment by eric-lian** [comment]
问题是解决了，但并没有找出问题那 ~
