### ISSUE TITLE
怎么让下载运行在另一个进程中？

### ISSUE THREAD

**Issue by hywenbinger** [lingochamp/okdownload#26]
您好，okdownload有类似filedownloader的配置process.non-separate=true吗？可以使下载服务运行在其他进程中。

**Comment by Jacksgong** [comment]
由于在大多数场景下载在独立进程中运行下载服务这个是比较特殊的场景，在目前的版本中还没有实现这个独立进程运行下载服务的特性，不过在未来的版本中我们会通过实现一个特定的`DownloadDispatcher`来实现这个特性，届时，可以通过类似引入`com.liulishuo.okdownload:process`，这样便会自动找到独立进程的`DownloadDispatcher`然后便会自动生效，就类似在[wiki](https://github.com/lingochamp/okdownload/wiki#import-okdownload-through-gradle)中说的与现在引入`okhttp`与`sqlite`组件一样。
