### ISSUE TITLE
重启应用已完成任务显示状态UNKNOWN

### ISSUE THREAD

**Issue by cdslily** [lingochamp/okdownload#265]
参照SingleActivity的实现，我针对同一个下载链接，当下在完成的时候，退出应用，贵司给的Sample能够正确显示completed，但是在我的应用中却始终是UNKNOWN,很惭愧我始终无法找到原因，你们能棒棒我吗？

**Comment by cdslily** [comment]
我尝试过依赖okdownload，甚至是下载源码后，直接依赖的okdownload library，也是一样的结果

**Comment by cdslily** [comment]
我debug了下 public static Status isCompletedOrUnknown(@NonNull DownloadTask task) 中store.isOnlyMemoryCache()一直为true，这个条件是在哪里设置的？

**Comment by cdslily** [comment]
我发现，Sample使用的Store是BreakpointStoreOnSQLite 而我的代码中默认构造出来的确实BreakpointStore。这个是在哪里配置的？

**Comment by cdslily** [comment]
case可以关掉了，原因是没有依赖sqlite导致的

**Comment by 1993xuge** [comment]
我这边 使用 发现。加上sqlite后，debug确实  没问题。但是release 有问题。下载成功后，总是返回UNKNOWN。我加上 
# okdownload:sqlite
-keep class com.liulishuo.okdownload.core.breakpoint.BreakpointStoreOnSQLite {
        public com.liulishuo.okdownload.core.breakpoint.DownloadStore createRemitSelf();
        public com.liulishuo.okdownload.core.breakpoint.BreakpointStoreOnSQLite(android.content.Context);
}

没啥用，还是UNKNOWN
