### ISSUE TITLE
OkDownload与FileDownloader的对比

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#27]
之前一直在使用FileDownloader的库，但是最近升级后发现一些问题，而且无法降级，想了解下，后续okdownload会替代之前的FileDownloader么，还有就是OkDownload会保持维护么

如果现在想在项目里引用新的OkDownload，是否可以与之前的FileDownloader可以共存？或者说，是否可以正常升级到OkDownload里

**Comment by Jacksgong** [comment]
正如[wiki](https://github.com/lingochamp/okdownload/wiki/Why-choose-OkDownload) 中提到的，OkDownload实际上室继承了所有FileDownloader的优点，我们也可以称为FileDownloader2，我们目前就已经为其做了更多的优化以及更多的特性，OkDownload会作为FileDownloader的延续。

FileDownloader仓库我们不会再新增需求以及其他大的改动，但是会保持小的Bug Fix，考虑到可维护性与稳定性，后续所有的新的特性以及优化等都只会在OkDownload中迭代。

**Comment by tomUp** [comment]
Hi，@Jacksgong
