### ISSUE TITLE
如何添加https请求的自签名证书支持

### ISSUE THREAD

**Issue by kjt666** [lingochamp/okdownload#271]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by zhangzhongxi** [comment]
//use you OkHttpBuilder 使用自己的OkhttpClient builder
           OkDownload.Builder builder = new OkDownload.Builder(Context);

            DownloadOkHttp3Connection.Factory factory = new DownloadOkHttp3Connection.Factory();
            //your builder
            factory.setBuilder(OkHttpHelper.getDownloadOkHttpBuilder());
            builder.connectionFactory(factory);

            try {
               //这里只能设置一次
                OkDownload.setSingletonInstance(builder.build());
            } catch (Exception e) {
                LogUtils.ds("download", "download init failed");
            }

**Comment by zhangzhongxi** [comment]
然后证书校验就是OkHttpClient里面去设置了，这个百度吧

**Comment by rantianhua** [comment]
请参考 https://www.jianshu.com/p/7c1bc2daef8d 。
