### ISSUE TITLE
How to pause and resume download

### ISSUE THREAD

**Issue by ravig252525** [lingochamp/okdownload#274]
How to pause and resume download

**Comment by jasonzhang1986** [comment]
我的理解是：可以直接 cancel就是暂停，再次执行下载会根据数据库中保存的 BreakInfo 和 block 来继续下载。

**Comment by rantianhua** [comment]
How to pause?
---
`DownloadTask#cancel()`.

How to resume?
---
`DownloadDispatcher#enqueue` or `DownloadDispatcher#execute`.

Just start a new task, OkDownload will download from the breakpoint.
