### ISSUE TITLE
在OkDownload中有没有类似FileDownloader的FileDownloadNetworkPolicyException

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#28]
在**FileDownloader**中，当网络断开或是从WIFI切到3G/4G的时候(设定下载为wifiOnly)会有一个**FileDownloadNetworkPolicyException** 的错误上报。

现在用**OkDownload**断开网络的时候会有一个**ERROR**的**EndCause**和一个**UnknownHostExecption**的**realCause**通过**taskEnd**上报上来，请问我是否可以通过这两个条件来判断是发生了断开网络的情况。还有就是如果我的task设定**wifiRequired为true**的情况下，当下载的过程中切换到3G/4G的时候，它会以什么形式来上报？还是说现在**OkDownload**只能自己来判断这一系列的操作？因为我看到这个问题 https://github.com/lingochamp/okdownload/issues/15 ，你说**FileDownloader**这是一个伪需求，所以我不知道在**OkDownload**中是否有比较官方一些的方法来判断网络切换的情况？
@Jacksgong

**Comment by Jacksgong** [comment]
以下情形是在`OkDownload`中设置了仅Wiki情况允许下载:

#### 下载过程中网络切换

由于在下载过程中，网络切换，实际上是先断开连接，再连接上新的网络状态，对于下载来说，由于连接被断开，得到的是以下错误

```
javax.net.ssl.SSLException: Read error: ssl=0x736daded00: I/O error during system call, Software caused connection abort
```

![image](https://user-images.githubusercontent.com/6176417/38781515-20295c16-4119-11e8-8e0e-b701a95129f7.png)

#### 在启动之前网络就已经是非Wiki状态，此时启动下载

此时会直接报`NetworkPolicyException`:

```
com.liulishuo.okdownload.core.exception.NetworkPolicyException: Only allows downloading this task on the wifi network type!
```

![image](https://user-images.githubusercontent.com/6176417/38781546-70ef10aa-4119-11e8-81af-ad9ed906fcc6.png)
