### ISSUE TITLE
4.4项目报错，找了半天才发现下载里面用了okhttp3.14.2版本，希望老铁们注意

### ISSUE THREAD

**Issue by alguojian** [lingochamp/okdownload#284]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by superzhangbao** [comment]
4.4的系统okhttp用3.12.0就可以了
