### ISSUE TITLE
在android5.0以下当使用TLSv1+的时候 下载失败

### ISSUE THREAD

**Issue by bomb987** [lingochamp/okdownload#288]
服务器使用TLSv1+版本，在Android的5.0以下版本会发生如下失败信息
cause = ERROR realCause = javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x674ad810: Failure in SSL library, usually a protocol error
请问该如何解决

**Comment by superzhangbao** [comment]
你可以尝试使用okhttp3.12.0版本，或者下载url https改为http

**Comment by rantianhua** [comment]
感谢 @superzhangbao 的回答。
