### ISSUE TITLE
怎么获取未下载任务列表？

### ISSUE THREAD

**Issue by BrickCar** [lingochamp/okdownload#292]
### OkDownload Version

v1.0.5-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
下载库内部有维护正在等待下载的任务列表，但是没有开放出接口来。不管你是单独下载还是同时下载若干个任务，都是有对应的监听器回调任务状态。你也可以通过 `OkDownload.downloadDispatcher().isPending(DownloadTask)` 来检查某个特定的任务是否在未下载任务列表里。
