### ISSUE TITLE
新手,怎么设置连接超时时间

### ISSUE THREAD

**Issue by kiss2sky** [lingochamp/okdownload#297]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by justLXX** [comment]
![image](https://user-images.githubusercontent.com/42031663/64603091-6d407d00-d3f2-11e9-96b9-9eea2c1c3da6.png)

![image](https://user-images.githubusercontent.com/42031663/64603170-8c3f0f00-d3f2-11e9-8208-82cef0310d2c.png)

**Comment by kiss2sky** [comment]
ok,thank you
