### ISSUE TITLE
想要通过taskId来clear或pause某个task的方法

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#30]
在原来FileDownloader里有一个操作就是clear，之前clear的操作从源码上看应该是先pause然后在去清除对应文件 ，现在OkDownload中好像并没有看到相应的clear操作，不知道有没有比较好的方法？从1.0.0的版本上要想自己清除下载文件，我是需要这样么？
`OkDownload.with().breakpointStore().remove(taskId) `
但是上面这个方法好像并没有暂停的功能吧？

我要是暂停的话是不是还需要:
`OkDownload.with().downloadDispatcher().cancel(task)`
但是问题来了，如果下载后，我只想通过taskId来进行 **暂停**和**清除**的功能，好像并不如之前FileDownloader里方便，如果只能通过task来暂停某个任务，在项目里还需要单独维护一个保存task的collection..
要么就是每次使用 **StatusUtils.createFinder()** 的方法再重新创建这个task，然后进行cancel，我看了下task的构造函数，还是有一些开销的

**Comment by Jacksgong** [comment]
`FileDownloader#clear`在okdownload 1.0.1中相当于:

```java
OkDownload.with().downloadDispatcher().cancel(id);
OkDownload.with().breakpointStore().remove(id);
new File(path).delete();
```

---

目前已经集成到1.0.1 snapshot，你可以通过[该方式](https://github.com/lingochamp/okdownload/wiki)引入测试。
