### ISSUE TITLE
在项目的SingleActivity中，多次点击START/CANCEL，有概率性出现timeout。

### ISSUE THREAD

**Issue by Heber-xu** [lingochamp/okdownload#303]
使用方式是直接把项目导下来，运行，加了日志，没改动其他代码。
只是打了这么一点日志：SingleActivity: taskEnd-realCause:timeout

**Comment by rantianhua** [comment]
Timeout 属于网络问题。

**Comment by Heber-xu** [comment]
是这样的，每当timeout之后，我马上干掉app，然后重启app，在到SingleActivity就可以了，所以，应该不是网络的问题。

**Comment by hywenbinger** [comment]
@rantianhua  我也遇到这个问题了，okdownload version是1.0.6，okhttp version是3.14.4。
看到1.0.7的milestones里有类似的issue，请问有具体更新计划吗？

**Comment by chenheqiang** [comment]
这个问题我也遇到了，我测试了一下可能是okhttp的线程池被快速挤满了，没有释放，导致新的无法连接上timeout，我试了试DownloadUrlConnection.Factory应该会好一些，楼上可以测试一下

**Comment by AreYReady** [comment]
是的，目前发现，同时请求两个task，会有一个成功一个失败。

**Comment by moneyBreak** [comment]
以身试法：昨天我单独将okhttp3升级到3.14.9,能解决楼主说的频繁暂停和继续会timeout的问题。  
如作者所说，这是okhttp池子的问题  
当然也不建议如楼上new多个client 。 之后要修复这个问题的小伙伴可以尝试。
如果你的项目支持直升4.x的版本那就更好了。因为我的工程环境问题，不支持kotlin编译.
