### ISSUE TITLE
https资源下载报错

### ISSUE THREAD

**Issue by shaoyu0829** [lingochamp/okdownload#307]
-Exception---javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
下载https资源报这个错

**Comment by equationl** [comment]
你用的是不是自签名的证书？是的话可以参考这个：
[ISSUE](https://github.com/lingochamp/okdownload/issues/271)。
不过我也没看懂这个怎么用，所以我又改回http了

**Comment by rantianhua** [comment]
Duplicate with #271 .

**Comment by pejayshang** [comment]
val sslContext = SSLContext.getInstance("TLS")
val trustAllCerts = arrayOf<TrustManager>(object : X509TrustManager {
	override fun checkClientTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}

	override fun checkServerTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}

	override fun getAcceptedIssuers(): Array<X509Certificate> {
		return arrayOf()
	}
})
sslContext.init(null, trustAllCerts, null)
val httpClientBuilder = OkHttpClient.Builder()
	.hostnameVerifier(HostnameVerifier { _, _ ->
		true
	})
httpClientBuilder.sslSocketFactory(
	sslContext.socketFactory,
	object : X509TrustManager {
		override fun checkClientTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}

		override fun checkServerTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}

		override fun getAcceptedIssuers(): Array<X509Certificate> {
			return arrayOf()
		}
	})
	
	OkDownload.setSingletonInstance(
	OkDownload.Builder(yourContext)
		.connectionFactory(DownloadOkHttp3Connection.Factory().setBuilder(httpClientBuilder))
		.build()

**Comment by pejayshang** [comment]
val sslContext = SSLContext.getInstance("TLS")
val trustAllCerts = arrayOf<TrustManager>(object : X509TrustManager {
	override fun checkClientTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}
	override fun checkServerTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}

	override fun getAcceptedIssuers(): Array<X509Certificate> {
		return arrayOf()
	}
})
sslContext.init(null, trustAllCerts, null)
val httpClientBuilder = OkHttpClient.Builder()
	.hostnameVerifier(HostnameVerifier { _, _ ->
		true
	})
httpClientBuilder.sslSocketFactory(
	sslContext.socketFactory,
	object : X509TrustManager {
		override fun checkClientTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}
		override fun checkServerTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}
		override fun getAcceptedIssuers(): Array<X509Certificate> {
			return arrayOf()
		}
	})
	OkDownload.setSingletonInstance(
	OkDownload.Builder(yourContext)
		.connectionFactory(DownloadOkHttp3Connection.Factory().setBuilder(httpClientBuilder))
		.build()

**Comment by pejayshang** [comment]
val sslContext = SSLContext.getInstance("TLS")
val trustAllCerts = arrayOf<TrustManager>(object : X509TrustManager {
	override fun checkClientTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}
	override fun checkServerTrusted(
		chain: Array<X509Certificate>,
		authType: String
	) {
	}
	override fun getAcceptedIssuers(): Array<X509Certificate> {
		return arrayOf()
	}
})
sslContext.init(null, trustAllCerts, null)
val httpClientBuilder = OkHttpClient.Builder()
	.hostnameVerifier(HostnameVerifier { _, _ ->
		true
	})
httpClientBuilder.sslSocketFactory(
	sslContext.socketFactory,
	object : X509TrustManager {
		override fun checkClientTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}
		override fun checkServerTrusted(
			chain: Array<X509Certificate>,
			authType: String
		) {
		}
		override fun getAcceptedIssuers(): Array<X509Certificate> {
			return arrayOf()
		}
	})
	OkDownload.setSingletonInstance(
	OkDownload.Builder(yourContext)
		.connectionFactory(DownloadOkHttp3Connection.Factory().setBuilder(httpClientBuilder))
		.build()
