### ISSUE TITLE
下载过程中大机率报socket timeout异常导致下载中断

### ISSUE THREAD

**Issue by chenyan-github** [lingochamp/okdownload#313]
### OkDownload Version
我使用的依赖库的版本如下：
implementation "com.liulishuo.okdownload:okdownload:1.0.5"
implementation "com.liulishuo.okdownload:sqlite:1.0.5"
implementation "com.liulishuo.okdownload:okhttp:1.0.5"
implementation "com.squareup.okhttp3:okhttp:3.11.0"

### Problem Describe

下载过程中有时会出现socket timeout导致下载中断，出现的机率较高，我用FileDownloader没发现过这种现象， 建议可以增加设置重试拦截器的接口，方便用户自定义重试机制。

**Comment by rantianhua** [comment]
OkDownload 去掉了重试配置，往往设置重试的意义不大，重试本身的逻辑还是纯粹交由使用者自己控制，最直接的是在 taskEnd 的回调里再重新进行下载。

**Comment by rantianhua** [comment]
SocketTimeout 问题本身已 OkDownload 无关，请在 OkHttp 的 Issue 里面查找。其实这类往往是因为网络问题产生的。
