### ISSUE TITLE
有没有从FileDownloader迁移到okdownload的文档

### ISSUE THREAD

**Issue by 1993xuge** [lingochamp/okdownload#315]
现在正在使用FileDownloader，但是FileDownloader有一个notification偶现，并且无法取消的问题。现在想迁移到okdownload，但是okdownload文档太少，并且demo中貌似没有在recyclerview中使用的介绍，所以不敢贸然迁移。

**Comment by rantianhua** [comment]
发现你在 https://github.com/lingochamp/FileDownloader/issues/1184 这里也在问了，已经提上日程，会多抽时间做的。

**Comment by 1993xuge** [comment]
好的，多谢，辛苦了！

**Comment by rantianhua** [comment]
请关注：https://github.com/lingochamp/okdownload/pull/331 。

**Comment by rantianhua** [comment]
专门写了一篇文章介绍如何迁移，请看 https://juejin.im/post/5dc527fcf265da4d3429ab5c 。
