### ISSUE TITLE
重复下载判断失败，每次都重新下。设置setPassIfAlreadyCompleted为true也没用

### ISSUE THREAD

**Issue by xivanglei** [lingochamp/okdownload#319]
机型 小米8se

**Comment by rantianhua** [comment]
抱歉，这样的 Issue 无法给您提供任何有效的帮助。请按照模板提供必要信息（尤其是日志），然后重新提个 Issue 吧，谢谢。

**Comment by gongkai193521** [comment]
我也遇到了，设置setPassIfAlreadyCompleted为true没用，每次都重新下，红米note8，Android版本9，没有日志

**Comment by gongkai193521** [comment]
看了下日志，下载完成后获取到状态是UNKNOWN
