### ISSUE TITLE
Run as Foreground Service

### ISSUE THREAD

**Issue by RowlandOti** [lingochamp/okdownload#320]
This is not problem reporting, but rather question on how to queue downloads in a background service, such that, even if the app is killed, and I resume the app, download status and progress can still be displayed.

Of course, with foreground, will have a notification with some information, but I  also would also have a list of the downloaded items displayed, and I would like that if the app is killed and resumed later, the download status should also update correctly for each item in the list i.e progress, speeds e.t.c

Also would like to scan android media URI/FILE once a download is complete. How can we get the downloaded file once it is complete?

**Comment by rantianhua** [comment]
> how to queue downloads in a background service?

You can use OkDownload in a service, in this way, the service is a background service or foreground service is totally determined by you.

> even if the app is killed, and I resume the app, download status and progress can still be displayed.

Please refer to [wiki](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline#iii-get-state-and-info). But sorry for that speed cannot be got through OkDownload after the app is killed.


> How can we get the downloaded file once it is complete?
DownloadTask supports uri and you can get the specific path through `DownloadTask#getFile()`.

**Comment by RowlandOti** [comment]
Thank, you, I think this answers it satisfactorily.   Brief and to the point.
