### ISSUE TITLE
关于断点问题

### ISSUE THREAD

**Issue by KnnethKong** [lingochamp/okdownload#337]
### OkDownload Version
    ####****
okdownload:1.0.5

### Problem Describe
1.有清空  已保存下载断点的方法吗。
2.能向FileDownloader 定制化数据库组件吗，哪个方法呢。
3. `摘取 QueueController`
`   val set = DownloadContext.QueueSet()
        val parentFile = File(DemoUtil.getParentFile(context), "queue")
        this.queueDir = parentFile

        set.setParentPathFile(parentFile)
        set.minIntervalMillisCallbackProcess = 200

        val builder = set.commit()

        var url = "http://dldir1.qq.com/weixin/android/weixin6516android1120.apk"
        var boundTask = builder.bind(url)
        TagUtil.saveTaskName(boundTask, "1. WeChat")

        url = "https://cdn.llscdn.com/yy/files/tkzpx40x-lls-LLS-5.7-785-20171108-111118.apk"
        boundTask = builder.bind(url)
        TagUtil.saveTaskName(boundTask, "2. LiuLiShuo")

        builder.setListener(listener)
        this.context = builder.build().also { this.taskList.addAll(it.tasks) }

      //下面又添加了一个下载task ⭐️ ⭐️ ⭐️ ⭐️
        url = "https://t.alipayobjects.com/L1/71/100/and/alipay_wap_main.apk"
        boundTask = builder.bind(url)
        TagUtil.saveTaskName(boundTask, "3. Alipay")
        taskList.add(boundTask)
`
上面代码在builder.build()执行后，再加个task 不会下载。
### Log###

**Comment by rantianhua** [comment]
> 1.有清空 已保存下载断点的方法吗。

`OkDownload.with().breakpointStore().remove(taskId);` ，在 [Wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline) 里面有提到。

> 2.能向FileDownloader 定制化数据库组件吗，哪个方法呢。

`OkDownload.Builder().downloadStore(DownloadStore)` ，在 [Wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component) 中也有示例。

> 3. builder.build()执行后，再加个task 不会下载。

`DownloadContext` 的用法就是提前准备好所有要下载的 Task ，当执行  Build 之后，需要下载的任务就构建好了。如果你想动态添加下载任务，应该使用 `DownloadSerialQueue` 。[Wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#iii-dynamic-serial-queue) 也有示例。
