### ISSUE TITLE
filedownload1文件下载文件大小错误为-1

### ISSUE THREAD

**Issue by TonyXie0320** [lingochamp/okdownload#37]

**Comment by Jacksgong** [comment]
okdownload中下载文件大小为 `-1` 为正常现象，当无法正确获知大小时，变为1，通常这种情况就会当作`chunked`资源进行下载。请留意日志，日志中会打出具体原因。建议参考[文档](https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload)适配okcat，使日志更加可读。
