### ISSUE TITLE
第一次请求建议使用HEAD请求

### ISSUE THREAD

**Issue by jiahuifu** [lingochamp/okdownload#390]
### OkDownload Version

v1.0.7

### Problem Describe

第一次获取信息的请求建议使用HEAD请求/后续断点下载GET

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
这块可以参照这篇文章的决策哈。

https://blog.dreamtobe.cn/tcp-window/

![image](https://user-images.githubusercontent.com/6176417/83759645-6ce5c180-a6a6-11ea-9cd9-75da68685dae.png)
