### ISSUE TITLE
没搞明白是怎么样给okhttp设置请求头的？

### ISSUE THREAD

**Issue by TangYuanHuan** [lingochamp/okdownload#42]
.setHeaderMapFields(map)好像没看到有把设置的请求头带过去

**Comment by Jacksgong** [comment]
其实，每个分块的的连接上是有带上的，具体参看代码`HeaderInterceptor#interceptConnect`，不过在试探连接(`BreakpointRemoteCheck`)中确实是没有带上，这个确实不符合预期，我加下。

**Comment by Jacksgong** [comment]
已经在`1.0.2-SNAPSHOT`上修复了该问题。

**Comment by TangYuanHuan** [comment]
哦哦，原来如此，我测试的是1.0.1版
