### ISSUE TITLE
The current offset on block-info

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#43]
作者您好，这个问题现在有头绪么？
https://github.com/lingochamp/okdownload/issues/31

**Comment by Jacksgong** [comment]
不好意思，最近工作上比较忙。

有关问题，我找时间会看的，我看你整理的很好，都有源码，其实最好的方式是你直接解决了，提PR，你可以先再看看。我抽空了，就回来看下。

> P.S. 我们自己也在使用okdownload的。

**Comment by kerneltea** [comment]
毕竟 流利说的源是自己提供的，很好控制 ，哎，我们这边的播客源千奇百怪的。
