### ISSUE TITLE
你好，有没有可以直接获取某一个下载任务进度的方法呢

### ISSUE THREAD

**Issue by leon0210** [lingochamp/okdownload#44]
例如像FileDownloader中的FileDownloader.getImpl().getSoFar（）、getTotal（）类似的方法，可以直接在外部获取下载信息

**Comment by Jacksgong** [comment]
参考[wiki-SampleUse-GetInfo](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline)，从Info中获得这些数据。
