### ISSUE TITLE
内存泄漏&&取消监听

### ISSUE THREAD

**Issue by Wangct23** [lingochamp/okdownload#45]
退出页面时如果没有cancel，那么监听Listener不会释放，这样会导致Listener所在的页面无法释放造成内存泄漏。
请问可否增加取消监听的api？
谢谢！

**Comment by Jacksgong** [comment]
可以采用[wiki-Advanced Use Guide-Dynamic Change Listener For tasks](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#v-dynamic-change-listener-for-tasks) 这个。
