### ISSUE TITLE
Cannot  add header [okdownload 1.0.7]

### ISSUE THREAD

**Issue by JackFromPremiumdev** [lingochamp/okdownload#454]
We just moved from the old Filedownloader to Okdownload the update was very flawless and it works greatly, we just have one problem we cannot add header in okdownload and its very important for us (we use a server with a custom user-agent )

here is the problem add header return void not builder:
![header_problem](https://user-images.githubusercontent.com/82322798/114306943-d52edc00-9add-11eb-8349-dc6869694281.JPG)

**Comment by mrdcd** [comment]
@JackFromPremiumdev  here is another api to set header
![image](https://user-images.githubusercontent.com/37876564/116665675-a1542180-a9cc-11eb-824d-7ba5d29c39f1.png)
