### ISSUE TITLE
RxJava支持

### ISSUE THREAD

**Issue by dengyuhan** [lingochamp/okdownload#50]
### OkDownload Version

v1.0.2

### Problem Describe

在介绍看到了支持RxJava,但是关于使用文档没有提到RxJava

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
所有的ToDo List在[这里](https://github.com/lingochamp/okdownload/wiki/Why-choose-OkDownload)可以看到，RxJava目前还没有支持，但是在计划中。
