### ISSUE TITLE
Re-attachListener for UnifiedListenerManager no process callback for DownloadListener1 DownloadListener4 DownloadListener4WithSpeed case

### ISSUE THREAD

**Issue by Wangct23** [lingochamp/okdownload#52]
场景：12个页面，每个页面有50个左右下载任务。在进入每个页面时都重新build task并attach listerner，退出当前页面时detachListerer，但是不会cancle下载。
这样在几个页面进出几次之后，停留在一个页面观察下载，一段时间后不再返回Listerner信息。这时退出页面再次进入也不会再返回Listener信息。

```
DownloadTask task = new DownloadTask.Builder(
                                    entity.getDownloadRecordTable().getMp4_url(),
                                    entity.getDownloadRecordTable().getParent_path(),
                                    entity.getDownloadRecordTable().getFilename())
                                    .setPriority(DOWNLOAD_PRIORITY_VIDEO)
                                    .setPassIfAlreadyCompleted(true)
                                    .build();

mUnifiedListenerManager.attachListener(task, taskDownloadListener);
```
```
mUnifiedListenerManager.detachListener(taskDownloadListener);
```

**Comment by Wangct23** [comment]
@Jacksgong 如果没有detachListener会不会导致内存泄漏呢？

**Comment by Wangct23** [comment]
https://github.com/Wangct23/okdownload.git

**Comment by Wangct23** [comment]
https://github.com/Wangct23/okdownload.git
进入 UniManagerActivity，start之后，退出页面再次进入UniManagerActivity。
Listener的回调就不会再调用。

**Comment by Jacksgong** [comment]
@Wangct23 这个是相对的，如果说你的`listener`是某个`Activity`或者`Fragment`的非静态内部类，或者本身就持有一些其他拥有固定生命周期的对象的引用，那么当这些对象根据生命周期结束，但是其引用在`listener`中没有被释放，并且该`listener`被另外一个更长生命周期的对象所引用，这里应该是`mUnifiedListenerManager`，那么就会导致泄露。

因此，你只要保证`listener`中对`Activity`或者`Fragment`之类UI相关有固定申明对象的引用，在其生明周期结束时被释放就可以了，而无需`detachListener`。

---

好的，你的这个demo，我抽空的时候会看下，今天公司有点事情，最晚我这周末给你看下，你也可以根据我的建议自行看下，或者采用释放对UI相关生命周期对象引用即可来验证解决。

**Comment by Jacksgong** [comment]
我看了你的demo。

> 由于你这个是demo，我们只谈issue中谈到的Listener不回调的问题

---

1. `UnifiedListenerManager` 在这个 `UniManagerActivity`中是一个成员变量，因此每次创建都是一个新的`Manager` ==> **这里是使用的问题，你需要将其放在一个单例的地方，保证前后是同一个`UnifiedListenerManager`实例。**
2. `DownloadListener1`, `DownloadListener4`, `DownloadListener4WithSpeed` 这几个监听器内部有单独的一个数据模型，而这个数据模型是跟随回调的生命周期创建与删除的，因此在重新创建监听在`attach`到`Manager`中的时候，由于创建模型的生命周期已过，所以内部的所有除`taskEnd`的回调都被直接屏蔽了 ==> **对于接口设计来说，这是一个BUG，我会尽快在 1.0.3-SNAPSHOT 上对其进行修复**

**Comment by Jacksgong** [comment]
现在这个BUG已经在`1.0.3-SNAPSHOT`上修复了，你可以参考[wiki](https://github.com/lingochamp/okdownload/wiki)引入该SNAPSHOT版本进行验证，需要特别注意的是，你上层需要注意修复采用新`UnifiedListenerManager`的问题（改用单例或者是静态变量）。

---

存在小概率`attach`的时候刚好下载完成导致没有进度的问题，这个你参考下[这里](https://github.com/lingochamp/okdownload/issues/52#issuecomment-385841321)提到的温馨提示。
