### ISSUE TITLE
现在的1.0.2版本 没有非常全面的中文文档

### ISSUE THREAD

**Issue by operatium** [lingochamp/okdownload#53]
针对现在的1.0.2版本 没有非常全面的中文文档，无法替换之前的FileDownloader

**Comment by Jacksgong** [comment]
其实，只要稍微看一眼[Wiki](https://github.com/lingochamp/okdownload/wiki) 就会明白，Wiki虽然是英文的，但是已经是非常简单，从[Simple Use Guide](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline)到[Advanced Use Guide](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline)总共涉及的英语单词非常少。

我认为优秀的接口设计，接口本身就能够足够充分的表达符合预期的设定，复杂且庞大的文档并不能说明该库可靠，反而说明了该库接口设计存在问题。

希望你看一眼wiki，我认为绝大多数的同学，看一眼[Simple Use Guide](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline)与[Advanced Use Guide](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline)后便能轻松上手，甚至看了[Debug OkDownload](https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload)后能够一起参与开发。而项目中还有精心设计的Sample Project, 这个项目从`MainActivity`入口，到`SingleActivity`、`EachBlockProgressActivity`、`QueueActivity`、`BunchActivity`、`ContentUriActivity`、`NotificationActivity`每个都是以尽可能可读的代码来诠释库的主要功能。

**Comment by imaiya** [comment]
作为英文不是很好的开发者,也还是希望能有一份中文文档
