### ISSUE TITLE
下载支持 CDN 的大文件容易出现异常

### ISSUE THREAD

**Issue by xlrei** [lingochamp/okdownload#54]
### OkDownload Version

v1.0.2（未添加 okhttp 支持）

### Problem Describe

下载支持 CDN 的 apk 文件（600M）容易在下载途中出现如下异常

### Log
```
 javax.net.ssl.SSLProtocolException: Read error: ssl=0xba479500: Failure in SSL library, usually a protocol error error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

**Comment by xuanu** [comment]
小文件也一样，老是提示什么 cu..416 offset 0.的。
但是我只要用浏览下载一次，又能下载成功了。

**Comment by Jacksgong** [comment]
@xlrei 我有在网络上稍微查了下，首先你这个错误并非okdownload这一层抛出的错误，而是tls这一层校验跑出来的，反而更像是后端openssl服务的错误，我根据错误信息提示，猜测应该是后端这边openssl这边有关版本号错误。

因此相关错误请咨询你的后端同学，或者是CDN供应商，谢谢。

----

@xuanu 你的问题我并不清楚，可否尝试通过日志等途径获得有效信息，如果存在问题从日志无法得到解决，请提供完整的信息，并且提交新的Issue。

**Comment by qq2748** [comment]
我也出现这个问题了  请问解决了吗
