### ISSUE TITLE
CDN文件下载失败

### ISSUE THREAD

**Issue by xuanu** [lingochamp/okdownload#55]
一定不能通过网页访问，如果访问一次，再通过okdownlaod下载就可以了。
下载地址：com.liulishuo.okdownload.DownloadTask@cd4e2add@3@http://cdn.qimonjy.cn:80//netstudy/main/aibooks/20180107/201801071145582596914048/c649b25069a241caa6f77423be5754ef.jpg@/storage/emulated/0/qimon/student/cache/common/ppts.com/24/2446C9854484EF08E2F5670A177609B4.jpg

![tim 20180507095546](https://user-images.githubusercontent.com/7351758/39681451-dda83914-51dc-11e8-9d65-4f90feb3eea8.png)

**Comment by Jacksgong** [comment]
1. 这个和CDN没有直接关系
2. 这个问题实际上是你们后端处理的问题，根据[rfc7233](https://tools.ietf.org/html/rfc7233)协定的http协议，当请求头请求的Range是`0-0`时，仅返回第一个与最后一个字节，可是你们后端直接返回416(Range Not Satisfiable), 这明显不符合HTTP协议；准确上来说，这是你们后端http协议层面的问题
3. 但是理论上来说返回416的时候，应该不带回有效数据，但是后端却是带回了有效数据，因此这边没有做进一步的HEAD补偿性试探请求，因此到后面直接检查`response code`的时候就不过了

![image](https://user-images.githubusercontent.com/6176417/39682421-5893c4e0-51e2-11e8-8945-8a56482e78b9.png)

---

- 针对为什么OkDownload的试探链接需要采用Range `0-0`的原因，请参看[这篇](https://blog.dreamtobe.cn/tcp-window/)文章

---

- 试探性连接相关代码: `ConnectTrial.java`
- 响应检查相关代码: `BreakpointRemoteCheck.java`

---

不过你这种情况的特征也比较明显，那就是对于试探链接，后端返回 `416`(其实按照协议此时是不可能出现`416`的，因为我们并没有提供除`0-0`以外的Range)，但是响应头的数据都是有效的，**因此，考虑到可用性，我们这边已经在1.0.3-SNAPSHOT`特别将这种情况处理为合法，你可以根据[wiki](https://github.com/lingochamp/okdownload/wiki)引入snapshot版本进行下载此类不符合协议类型的资源了**
