### ISSUE TITLE
下载防盗链思路

### ISSUE THREAD

**Issue by hongyang51** [lingochamp/okdownload#56]
### OkDownload Version

v1.0.2-SNAPSHOT

```
下载防盗链链接 如何控制断点续传? 思路 谢谢! 
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
参考[wiki-qa](https://github.com/lingochamp/okdownload/wiki/QA#how-to-set-my-own-task-id-generation-function)
