### ISSUE TITLE
下载文件失败.

### ISSUE THREAD

**Issue by FollowMeWang** [lingochamp/okdownload#6]
当我用demo下载文件时,下载连接里面带有参数的时候(exp: url = xxxxx/thunt/get?t=f&id=c ),能够正常连接到服务器，文件读取成功，但是在调用MultiPointOutputStream类的inspectComplete() 方法时会抛出一个IO 异常（exp: The current offset on block-info isn't update correct, 225508 != 0 on 0 ）.如果我用 FileDownloader 下载此文件能够正常下载的.

**Comment by Jacksgong** [comment]
这个问题应该在最新的master分支已经修复。

**Comment by Harvey0724** [comment]
这个 问题还是出现,DownloadListener 回调的文件长度为0

**Comment by FollowMeWang** [comment]
通过get 方法请求网络啊 ，能够正常连接上，但是下载的文件总大小为

**Comment by FollowMeWang** [comment]
通过get 方法请求网络啊 ，能够正常连接上，但是下载回调里的文件总大小为0.结束时会跑抛出异常（exp: The current offset on block-info isn't update correct, 225508 != 0 on 0 ）

**Comment by FollowMeWang** [comment]
这个问题还是存在的。通过get 方法请求网络啊 ，能够正常连接上，但是下载回调里的文件总大小为0.结束时会跑抛出异常（exp: The current offset on block-info isn't update correct, 225508 != 0 on 0 ）
