### ISSUE TITLE
ServerCanceledException: Response code can't handled on internal 416 with current offset 0

### ISSUE THREAD

**Issue by xlrei** [lingochamp/okdownload#60]
### OkDownload Version
v1.0.2

### Problem Describe

下载 CDN apk 链接有概率出现 ServerCanceledException 异常，提示 416 错误，查相关错误貌似是下载请求传参（RANGE 信息）异常，参考资料：
https://www.cnblogs.com/chenpingzhao/p/5797506.html

### Log

```
 com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 416 with current offset 0 
```

**Comment by Jacksgong** [comment]
416错误，不一定是Range有问题，也有可能是服务端返回错误，okdownload中Range错误的概率很低，并且你提供这样的信息完全无法进一步定位问题。

1.  你确定下是否是 https://github.com/lingochamp/okdownload/issues/55#issuecomment-386949516提到的相同的情况，如果是引入1.0.3-SNAPSHOT即可解决
2. 如果不是 #55 这种服务端问题，请提供完整的日志，或者提供有问题的URL以便于进一步定位问题，最好是自己通过[适配可读日志](https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload)，自己直接找到原因

**Comment by Jacksgong** [comment]
okay，那就是与 https://github.com/lingochamp/okdownload/issues/55#issuecomment-386949516 相通的问题，这个是这个cdn后端的bug，我们我们在 1.0.3-SNAPSHOT 中做了适配，你参考 [wiki](https://github.com/lingochamp/okdownload/wiki) 引入 1.0.3-SNAPSHOT版本即可修复。

**Comment by Jacksgong** [comment]
通过这一行日志我能获知的这个并非okdownload的问题，而是网络或者后端问题，这类问题在[FileDownloader issue](https://github.com/lingochamp/FileDownloader/search?q=ProtocolException&type=Issues)已经解释的够多了，请遇到问题先google，issue看wiki再尝试自行解决PR，最后再提Issue，来提高问题的解决效率，谢谢。

**Comment by xlrei** [comment]
@Jacksgong 的确是网络或后端问题，但 okdownload 难道不应该做一定的兼容尽量避免这类问题吗？

之前我没有使用 okhttp 组件，按照网上的解决方案，添加上该组件即能解决问题，但建议做好兼容，不然对于有问题的后端网络，出现异常的概率是极高的。

**Comment by Jacksgong** [comment]
@xlrei FileDownloader也是我们写的第一代的开源下载项目，okdownload是FileDownloader2，该问题无论使用什么下载库都同样存在。如果不存在只有可能会引发其他的错误，因为这个不是端上的问题，并不存在兼容一说。

如果你的后端频繁的出现该问题，你应该解决的是后端的问题，或者是网络层的问题，而非okdownload的问题。

不过如果你预研下来有更好的解决方案，也十分欢迎提PR或者直接提出解决方案。

**Comment by ZKXSparke** [comment]
com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 200 with current offset 232386245  我也出现这个情况了，不过是200，有大神能解答一下吗

**Comment by zhuqichao** [comment]
com.liulishuo.okdownload.core.exception.ServerCanceledException: Response code can't handled on internal 404 with current offset 0
遇到同样问题，但是是404，求解

**Comment by sunshengfei** [comment]
Response code can't handled on internal 404 with current offset 0
哎，自己写吧
