### ISSUE TITLE
按照的文档导入库后在android4.0的设备上就提示 Could not find class 'okhttp3.OkHttpClient', referenced from method com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection$Factory.create

### ISSUE THREAD

**Issue by zdc212133** [lingochamp/okdownload#65]
demo在android5.0以下设备上也是无法运行，文档描述不够全面

**Comment by Jacksgong** [comment]
可否提供完整堆栈，sample project是在android 5.0以及以上没有这个问题，在android 5.0以下就会有这个问题吗?

**Comment by zdc212133** [comment]
按照你的文档，创建了一个空的项目，添加了   
   implementation 'com.liulishuo.okdownload:okdownload:1.0.3'
    implementation 'com.liulishuo.okdownload:sqlite:1.0.3'
    implementation 'com.liulishuo.okdownload:okhttp:1.0.3' 调用了下载就项目就直接崩了 
下载Task
    private static DownloadTask createTask(DownloadInfo info){
        return new DownloadTask.Builder(info.getUrl(),info.getFilePath(),info.getFileName())
                .setMinIntervalMillisCallbackProcess(64)
                .setPassIfAlreadyCompleted(false)
                .build();
    }
奔溃日志：
05-17 18:16:01.822 24982-24982/read.tst.com.downloadt E/dalvikvm: Could not find class 'okhttp3.OkHttpClient', referenced from method com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection$Factory.create
05-17 18:16:01.822 24982-24982/read.tst.com.downloadt W/dalvikvm: VFY: unable to resolve new-instance 2939 (Lokhttp3/OkHttpClient;) in Lcom/liulishuo/okdownload/core/connection/DownloadOkHttp3Connection$Factory;
05-17 18:16:01.822 24982-24982/read.tst.com.downloadt D/dalvikvm: VFY: replacing opcode 0x22 at 0x0016
05-17 18:16:01.822 24982-24982/read.tst.com.downloadt W/dalvikvm: VFY: unable to find class referenced in signature (Lokhttp3/OkHttpClient;)
05-17 18:16:01.822 24982-24982/read.tst.com.downloadt D/dalvikvm: DexOpt: unable to opt direct call 0x5c09 at 0x06 in Lcom/liulishuo/okdownload/core/connection/DownloadOkHttp3Connection$Factory;.builder
    DexOpt: unable to opt direct call 0x5c0b at 0x18 in Lcom/liulishuo/okdownload/core/connection/DownloadOkHttp3Connection$Factory;.create
05-17 18:16:01.842 24982-25013/read.tst.com.downloadt W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x40df7930)
    
    --------- beginning of /dev/log/system
05-17 18:16:01.842 24982-25013/read.tst.com.downloadt E/AndroidRuntime: FATAL EXCEPTION: OkDownload Download
    java.lang.NoClassDefFoundError: okhttp3.OkHttpClient
        at com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection$Factory.create(DownloadOkHttp3Connection.java:125)
        at com.liulishuo.okdownload.core.download.ConnectTrial.executeTrial(ConnectTrial.java:73)
        at com.liulishuo.okdownload.core.download.BreakpointRemoteCheck.check(BreakpointRemoteCheck.java:100)
        at com.liulishuo.okdownload.core.download.DownloadCall.execute(DownloadCall.java:170)
        at com.liulishuo.okdownload.core.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)
05-17 18:16:01.852 431-1774/? W/ActivityManager:   Force finishing activity read.tst.com.downloadt/.MainActivity

**Comment by Jacksgong** [comment]
ok，我知道你原因了，这个和系统版本没有关系。是因为你使用了`com.liulishuo.okdownload:okhttp`单是没有引用okhttp导致的。你可以参照[okhttp](https://github.com/square/okhttp)的文档，引入okhttp进行解决，如下:

```
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
```

相关的我已经在[wiki](https://github.com/lingochamp/okdownload/wiki)上进行更新了，多谢提醒。

**Comment by zdc212133** [comment]
好的，谢谢
