### ISSUE TITLE
我新上传到服务器上的文件，使用这个库下载时，最低需要5秒后才能正常下载，在浏览器上是可以正常下载的

### ISSUE THREAD

**Issue by zdc212133** [lingochamp/okdownload#66]

**Comment by zdc212133** [comment]
异常信息：com.liulishuo.okdownload.core.exception.ResumeFailedException: Resume failed because of RESPONSE_PRECONDITION_FAILED

**Comment by Jacksgong** [comment]
1. 我不是很明白，最低需要5秒后才能正常下载是什么意思？一个任务的启动一般是在5毫秒内完成(这里是[测试报告](https://github.com/lingochamp/okdownload/issues/46#issuecomment-385018476))，这和浏览器下载有什么直接关系？
2. 这个错误信息很明确了，后端返回的与本地比对校验`precondition`失败，因此取消该次断点续传，该次下载从头开始。

> 友情提示，如果在网络状况较差的情况下，有可能网络建连需要很久，这块请关注`DownloadListener`每一个节点的回调距离下一个节点日志的时间间隔来获知。

**Comment by zdc212133** [comment]
我用HttpUrlconnection下载当前文件是正常，用你的这个库下载就失败，但过了5秒左右时间再去用你的库去下载这个文件就正常。

**Comment by Jacksgong** [comment]
@zdc212133 下载失败，具体的错误信息是什么？可否提供具体的日志信息？

**Comment by zdc212133** [comment]
我在TaskEnd里面打印了realCause 就只是com.liulishuo.okdownload.core.exception.ResumeFailedException: Resume failed because of RESPONSE_PRECONDITION_FAILED

**Comment by zdc212133** [comment]
这是我的使用    
public void download(DownloadCallback cb){
        task.setTag("mark-task-started");
        DownloadListener4WithSpeed listener4WithSpeed=createSampleListener(cb);
        task.enqueue(listener4WithSpeed);
    }
    /**
     * 创建下载任务
     * @param info
     * @return
     */
    private  DownloadTask createTask(DownloadInfo info){
        Log.i(TAG,"download url:"+info.getUrl()+"--filepath"+info.getFilePath()+"--filename:"+info.getFileName());
        File parentFile=new File(info.getFilePath());
        String parentUrl=info.getUrl();
        String fileName=info.getFileName();
        return new DownloadTask.Builder(parentUrl,parentFile)
                .setFilename(fileName)
                .setMinIntervalMillisCallbackProcess(64)
                .setPassIfAlreadyCompleted(false)
                .build();
    }

    private  DownloadListener4WithSpeed createSampleListener(final DownloadCallback cb) {
        return new DownloadListener4WithSpeed() {
            long totalLength;
            @Override
            public void taskStart(@NonNull DownloadTask task) {
                Log.i(TAG,"task Start download:");
            }
            @Override
            public void connectStart(@NonNull DownloadTask task, int blockIndex, @NonNull Map<String, List<String>> requestHeaderFields) {
                Log.i(TAG,"task connectStart");
            }
            @Override
            public void connectEnd(@NonNull DownloadTask task, int blockIndex, int responseCode, @NonNull Map<String, List<String>> responseHeaderFields) {
                Log.i(TAG,"task connectEnd");
            }
            @Override
            public void infoReady(@NonNull DownloadTask task, @NonNull BreakpointInfo info, boolean fromBreakpoint, @NonNull Listener4SpeedAssistExtend.Listener4SpeedModel model) {
                totalLength=info.getTotalLength();
                Log.i(TAG,"task infoReady"+totalLength);
            }
            @Override
            public void progressBlock(@NonNull DownloadTask task, int blockIndex, long currentBlockOffset, @NonNull SpeedCalculator blockSpeed) {
                Log.i(TAG,"task progressBlock");
            }
            @Override
            public void progress(@NonNull DownloadTask task, long currentOffset, @NonNull SpeedCalculator taskSpeed) {
                float percent = (float) currentOffset / totalLength;
                cb.progress((int)(percent*100));
                Log.i(TAG,"task progress"+percent);
            }
            @Override
            public void blockEnd(@NonNull DownloadTask task, int blockIndex, BlockInfo info, @NonNull SpeedCalculator blockSpeed) {
                Log.i(TAG,"task blockEnd:");
            }
            @Override
            public void taskEnd(@NonNull DownloadTask task, @NonNull EndCause cause, @Nullable Exception realCause, @NonNull SpeedCalculator taskSpeed) {
                Log.i(TAG,"task end download"+cause+"--"+realCause.getMessage());
                task.setTag(null);
                if (cause==EndCause.COMPLETED){
                    cb.success();
                }else if (cause==EndCause.ERROR){
                    cb.fail();
                }
            }
        };
    }

**Comment by zdc212133** [comment]
这是我这边打印的日志，这个地址是局域网内的
05-18 16:11:01.552 24276-24276/DownloadServer: download url:http://192.168.30.5/Administrator/note/10070.png--filepath/mnt/sdcard/iclass/kz/download/blackboard/tmp--filename:10070.png
05-18 16:11:01.922 24276-24276/com.invosas.mdc I/DownloadServer: task Start download:
05-18 16:11:02.082 24276-24276/com.invosas.mdc I/DownloadServer: task infoReady298242
    task connectStart
    task connectEnd
    task infoReady298242
    task connectStart
    task connectEnd
    task end downloadERROR--Resume failed because of RESPONSE_PRECONDITION_FAILED

**Comment by zdc212133** [comment]
我们这边是千兆无线局域网，不会存在网络连接问题。

**Comment by zdc212133** [comment]
最新捕获到的异常
05-18 16:52:01.402 30112-30386/ W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
05-18 16:52:01.412 30112-30386/ W/dalvikvm: VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
05-18 16:52:01.412 30112-30386/ I/dalvikvm: Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
05-18 16:52:01.412 30112-30386/W/dalvikvm: VFY: unable to resolve static method 33986: Ljava/nio/file/Files;.newOutputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/OutputStream;
05-18 16:52:01.412 30112-30386/D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
05-18 16:52:01.412 30112-30386/ W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
    VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
05-18 16:52:01.412 30112-30386/I/dalvikvm: Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
05-18 16:52:01.412 30112-30386/ W/dalvikvm: VFY: unable to resolve static method 33985: Ljava/nio/file/Files;.newInputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;
05-18 16:52:01.412 30112-30386/ D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a

**Comment by Jacksgong** [comment]
@zdc212133 可否提供下全部的日志信息?

**Comment by zdc212133** [comment]
这是我使用你的demo测试的日志信息：
05-18 18:13:23.962 115-346/? I/alsa_mix: -->Playback Path access 3
05-18 18:13:23.962 3897-3897/com.liulishuo.okdownload.sample D/DownloadDispatcher: enqueueLocked for single task: com.liulishuo.okdownload.DownloadTask@37921d74@2@http://192.168.30.5/Administrator/note/10083.png@/data/data/com.liulishuo.okdownload.sample/cache/each-block-progress-test
05-18 18:13:23.962 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: taskStart: 2
05-18 18:13:24.042 3897-3897/com.liulishuo.okdownload.sample I/EachBlockProgress: taskStart:
05-18 18:13:24.062 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start trial task(2) {range=[bytes=0-0]}
05-18 18:13:24.102 3897-4014/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
    VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
05-18 18:13:24.102 3897-4014/com.liulishuo.okdownload.sample I/dalvikvm: Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
05-18 18:13:24.102 3897-4014/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to resolve static method 24455: Ljava/nio/file/Files;.newOutputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/OutputStream;
05-18 18:13:24.102 3897-4014/com.liulishuo.okdownload.sample D/dalvikvm: VFY: replacing opcode 0x77 at 0x0002
05-18 18:13:24.102 3897-4014/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
    VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
05-18 18:13:24.112 3897-4014/com.liulishuo.okdownload.sample I/dalvikvm: Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
05-18 18:13:24.112 3897-4014/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to resolve static method 24454: Ljava/nio/file/Files;.newInputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;
05-18 18:13:24.112 3897-4014/com.liulishuo.okdownload.sample D/dalvikvm: VFY: replacing opcode 0x77 at 0x0002
05-18 18:13:24.132 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish trial task(2) code[206]{accept-ranges=[bytes], content-length=[1], content-range=[bytes 0-0/291965], content-type=[image/png], date=[Fri, 18 May 2018 10:12:38 GMT], etag=[W/"5ace3c090eed31:0"], last-modified=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-IIS/7.5], x-powered-by=[ASP.NET]}
05-18 18:13:24.132 3897-4014/com.liulishuo.okdownload.sample D/DownloadDispatcher: is file conflict after run: 2
05-18 18:13:24.132 3897-4014/com.liulishuo.okdownload.sample D/DownloadCall: breakpoint invalid: download from beginning because of local check is dirty 2 fileExist[true] infoRight[false] outputStreamSupport[true] com.liulishuo.okdownload.core.download.BreakpointLocalCheck@412d4358
05-18 18:13:24.132 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: downloadFromBeginning: 2
05-18 18:13:24.172 3897-4018/com.liulishuo.okdownload.sample D/HeaderInterceptor: AssembleHeaderRange (2) block(0) downloadFrom(0) currentOffset(0)
05-18 18:13:24.182 3897-4018/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start connection task(2) block(0) {if-match=[W/"5ace3c090eed31:0"], range=[bytes=0-291964], user-agent=[OkDownload/1.0.3-SNAPSHOT]}
05-18 18:13:24.222 3897-4018/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish connection task(2) block(0) code[412]{connection=[close], content-length=[331], content-type=[text/html; charset=us-ascii], date=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-HTTPAPI/2.0]}
05-18 18:13:24.232 3897-4019/com.liulishuo.okdownload.sample D/DownloadChain: release connection com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection@412dabb8 task[2] block[0]
05-18 18:13:24.232 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start trial task(2) {range=[bytes=0-0]}
05-18 18:13:24.232 3897-4009/com.liulishuo.okdownload.sample D/RemitSyncExecutor: remove info 2
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample I/dalvikvm: DexOpt: illegal method access (call Landroid/widget/ProgressBar;.setProgress (IZ)V from Lcom/liulishuo/okdownload/sample/util/ProgressUtil;)
    Could not find method android.widget.ProgressBar.setProgress, referenced from method com.liulishuo.okdownload.sample.util.ProgressUtil.calcProgressToViewAndMark
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to resolve virtual method 21859: Landroid/widget/ProgressBar;.setProgress (IZ)V
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample D/dalvikvm: VFY: replacing opcode 0x6e at 0x0020
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample I/dalvikvm: DexOpt: illegal method access (call Landroid/widget/ProgressBar;.setProgress (IZ)V from Lcom/liulishuo/okdownload/sample/util/ProgressUtil;)
    Could not find method android.widget.ProgressBar.setProgress, referenced from method com.liulishuo.okdownload.sample.util.ProgressUtil.updateProgressToViewWithMark
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample W/dalvikvm: VFY: unable to resolve virtual method 21859: Landroid/widget/ProgressBar;.setProgress (IZ)V
05-18 18:13:24.242 3897-3897/com.liulishuo.okdownload.sample D/dalvikvm: VFY: replacing opcode 0x6e at 0x001b
05-18 18:13:24.242 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: <----- finish trial task(2) code[206]{accept-ranges=[bytes], content-length=[1], content-range=[bytes 0-0/291965], content-type=[image/png], date=[Fri, 18 May 2018 10:12:38 GMT], etag=[W/"5ace3c090eed31:0"], last-modified=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-IIS/7.5], x-powered-by=[ASP.NET]}
05-18 18:13:24.242 3897-4014/com.liulishuo.okdownload.sample D/DownloadDispatcher: is file conflict after run: 2
05-18 18:13:24.242 3897-4014/com.liulishuo.okdownload.sample D/DownloadCall: breakpoint invalid: download from beginning because of local check is dirty 2 fileExist[false] infoRight[false] outputStreamSupport[true] com.liulishuo.okdownload.core.download.BreakpointLocalCheck@412ebfe0
05-18 18:13:24.242 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: downloadFromBeginning: 2
05-18 18:13:24.252 3897-4018/com.liulishuo.okdownload.sample D/HeaderInterceptor: AssembleHeaderRange (2) block(0) downloadFrom(0) currentOffset(0)
05-18 18:13:24.252 3897-4018/com.liulishuo.okdownload.sample D/CallbackDispatcher: -----> start connection task(2) block(0) {if-match=[W/"5ace3c090eed31:0"], range=[bytes=0-291964], user-agent=[OkDownload/1.0.3-SNAPSHOT]}
    <----- finish connection task(2) block(0) code[412]{connection=[close], content-length=[331], content-type=[text/html; charset=us-ascii], date=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-HTTPAPI/2.0]}
05-18 18:13:24.252 3897-4019/com.liulishuo.okdownload.sample D/DownloadChain: release connection com.liulishuo.okdownload.core.connection.DownloadOkHttp3Connection@412ecde8 task[2] block[0]
05-18 18:13:24.262 3897-4014/com.liulishuo.okdownload.sample D/CallbackDispatcher: taskEnd: 2 ERROR com.liulishuo.okdownload.core.exception.ResumeFailedException: Resume failed because of RESPONSE_PRECONDITION_FAILED
05-18 18:13:24.262 3897-4009/com.liulishuo.okdownload.sample D/RemitSyncExecutor: sync info with id: 2
    remove free bunch id 2
05-18 18:13:24.262 3897-4014/com.liulishuo.okdownload.sample D/DownloadCall: call is finished 2
05-18 18:13:24.282 3897-3897/com.liulishuo.okdownload.sample I/EachBlockProgress: taskEnd:

**Comment by Jacksgong** [comment]
根据日志已经获知原因:

```
-----> start connection task(2) block(0) {if-match=[W/"5ace3c090eed31:0"], range=[bytes=0-291964], user-agent=[OkDownload/1.0.3-SNAPSHOT]}
<----- finish connection task(2) block(0) code[412]{connection=[close], content-length=[331], content-type=[text/html; charset=us-ascii], date=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-HTTPAPI/2.0]}
```

如上，发起一个常规的`GET`请求，服务端直接返回`412`，该`response code`的含义就是`Precondition failed`所以这样的错误返回是符合预期的。

该问题，应该是你的后端服务写的有问题。

第一个分块收到`412`响应的请求头:

```
 {if-match=[W/"5ace3c090eed31:0"], range=[bytes=0-291964], user-agent=[OkDownload/1.0.3-SNAPSHOT]}
```

该请求头的`if-match`数据是在试探连接中获得的:

```
-----> start trial task(2) {range=[bytes=0-0]}
<----- finish trial task(2) code[206]{accept-ranges=[bytes], content-length=[1], content-range=[bytes 0-0/291965], content-type=[image/png], date=[Fri, 18 May 2018 10:12:38 GMT], etag=[W/"5ace3c090eed31:0"], last-modified=[Fri, 18 May 2018 10:12:38 GMT], server=[Microsoft-IIS/7.5], x-powered-by=[ASP.NET]}
```

---

#### 友情提示

通常这个`Precondition Failed`的原因是通常是`if-match`发生的变更，但是此`if-match`是前几秒进行的试探连接获得的`etag`，根据协议，这说明该资源在几秒内资源发生了变动，也就是说在试探连接取回的长度以及文件内容已经被后端修改并发生了变化，直接返回`precondition failed`是符合预期的，并且通常来说资源频繁的被改动的情况是极低的。

**Comment by zdc212133** [comment]
我直接使用HttpUrlconnection去下载文件时可以正常的，是不是和请求头的配置有关系哪？你的请求头是否可以自定义。

**Comment by zdc212133** [comment]
我直接用HttpURLConnection 进行下载 可以正常下载 
设置如下：
            conn = (HttpURLConnection) url.openConnection();
            conn.setRequestProperty("Accept-Encoding", "identity");
            conn.setRequestMethod("GET");
            conn.setConnectTimeout(2*60*1000);
            conn.setReadTimeout(2*60*1000);

**Comment by Jacksgong** [comment]
以下情况不建议使用okdownload，建议自行通过`HttpUrlConnection`或是其他方式自行实现下载:

1. 为了适配你们自己的非HTTP协议的私有协议，并且该私有协议严重违背HTTP协议定义，okdownload一旦采取措施定义将会影响其他正常HTTP协议下的下载
2. 不需要分块，不需要断点续传的简单下载

---

你自行通过`HttpUrlconnection`去下载，对于这种不符合HTTP协议的后端，符合第二点与第一点:

1. 由于使用之前的`Etag`，在下一次一定会过期，所以断点续传必然失败
2. 由于`Etag`本身后台协议存在问题，该资源无法通过合规的分块下载

---

### 什么是合规的分块下载

在分块下载前通过试探请求`GET`带上请求头`range: 0-0`，返回文件长度，用于分块（如果`GET`返回不了文件长度，会使用`HEAD`再试一次）；而后在开始分块的时候，为了保证这几秒钟之间文件没有被修改，会带上试探请求返回的`Etag`用于校验，并且每一个分块都要保证该`Etag`有效，保证文件不被写脏。 而你这个`Etag`实时都在变化，只有两种情况:

1. 根据协议你后端的文件确实始终都在变化，这种只有一种情况: 这个是`chunked`资源，但是你的返回并没有告知是`chunked`而是给了明确的文件大小
2. 该资源后台不符合HTTP协议，在文件没有变更的情况下，始终自己返回的`Etag`失效，这种情况下，该资源无论如何是 1. 无法分块下载；2. 无法断点续传；如果抢行分块与断点，从协议层面这个文件始终会是脏文件 --  这种情况下okdownload引入没有太多意义，自行直接通过其他方式简单处理即可

---

OkDownload中会使用符合HTTP协议的两个简单的请求头:

1. `Range` -- 用于分块下载
2. `If-Match` -- 用于分块下载 与 断点续传 后端文件是否被修改校验 ** 你的问题就是，这个校验后台始终返回失败**

---

我有思考过是否是提供一个完全不需要这两个请求头的功能，比如就给两个参数，一个是`diableBreakpoint`，还有一个是`disableSplitBlock`，但是回过来想，如果说一个资源只是为了简单的回调，而根本就不需要断点续传与分块下载，此时是否是他们自行实现（可能就不到30行代码）会更轻量些？你觉得呢，不过这个需求我也在考虑中，欢迎交流。

**Comment by Godsbox** [comment]
我也出现了 这个问题  你是怎么解决的？

**Comment by zdc212133** [comment]
我自己实现的分块多线程断点续传。

**Comment by lijiahua** [comment]
> 我有思考过是否是提供一个完全不需要这两个请求头的功能，比如就给两个参数，一个是`diableBreakpoint`，还有一个是`disableSplitBlock`，但是回过来想，如果说一个资源只是为了简单的回调，而根本就不需要断点续传与分块下载，此时是否是他们自行实现（可能就不到30行代码）会更轻量些？你觉得呢，不过这个需求我也在考虑中，欢迎交流。

建议加上吧，如果开发者的应用需要从不同服务器上下东西(协议有支持分块也有不支持分块的)，按照目前的情况要通过两种下载方式(OKDownload+ HttpUrlconnection)实现，这样一点都不优雅。

**Comment by lijiahua** [comment]
另外我发现服务端返回的Content-Type 如果不是二进制流 也会出现楼主说的日志中报 RESPONSE_PRECONDITION_FAILED

下图是我在自己的一台NGINX服务器上的一个资源文件，最开始服务端返回的
Content-Type: text/plain; charset=utf-8,gbk,但是文件通过浏览器什么的都可以下载，用OKDownload就会报RESPONSE_PRECONDITION_FAILED，然后我在NGINX中对页面配置了下default_type，改成了application/octet-stream，如下图第二条命令结果，然后用OKDownload就可以正常下载。

![image](https://user-images.githubusercontent.com/4516554/45737325-0c87c580-bc20-11e8-83a2-89dd91423ff3.png)
