### ISSUE TITLE
流媒体视频文件该如何下载

### ISSUE THREAD

**Issue by Pancts** [lingochamp/okdownload#68]
### OkDownload Version

v1.0.3-SNAPSHOT

### Problem Describe

http头没有chunked, 也不包含Content-Length的流媒体资源

setConnectionCount设置为1

但是每次下载到800k左右就会完成下载, 请问怎么解决

### Log

D/CallbackDispatcher: -----> start trial task(4) {range=[bytes=0-0], user-agent=[android/4.0.0 (android 7.1.1; ; ONEPLUS+A3000)]}
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
W/ConnectTrial: Transfer-Encoding isn't chunked but there is no valid instance length found either!
D/CallbackDispatcher: <----- finish trial task(4) code[200]{access-control-allow-origin=[*], cache-control=[no-cache], connection=[close], content-type=[Flash], expires=[Sat, 19 May 2018 10:28:07 GMT], pragma=[no-cache], x-via=[1.1 PSlnlydxpi74:2 (Cdn Cache Server V2.0)[4 200 2]], x-ws-request-id=[5afffc37_PSlnlydxpi74_30876-48161]}
D/DownloadDispatcher: is file conflict after run: 4
D/DownloadCall: breakpoint invalid: download from beginning because of local check is dirty 4 fileExist[false] infoRight[false] outputStreamSupport[true] com.liulishuo.okdownload.core.download.BreakpointLocalCheck@8823987

**Comment by Jacksgong** [comment]
提供下完整的日志，或者是url?

**Comment by Pancts** [comment]
地址得抓一下 这个页面 
https://www.douyu.com/t/MDL2018  的JSON  https://www.douyu.com/lapi/live/getPlay/30

其中 rtmp_url + rtmp_live 
http://hdla.douyucdn.cn/live/30rKHCDJJLRKtLs6_550.flv?wsAuth=b1aa6ae73550f0d123245db5d7c3ccef&token=web-douyu-0-30-2ef1b497cea8aa144ea5049dcb080381&logo=0&expire=0&did=8d8f2c08c3be6384ffc5558500021501&ver=2018051611&pt=1&st=0

**Comment by Jacksgong** [comment]
你提供的连接返回是Forbidden 403。

而实际上OkDownload是支持chunked流媒体下载的，可是我通过你之前提供的日志获知该资源返回的并非流媒体，如果是动态大小的流媒体，那么根据协议，返回的响应头应该包含`Transfer-Encoding: chunked`，下面是你提供的日志:

···
D/CallbackDispatcher: <----- finish trial task(4) code[200]{access-control-allow-origin=[*], cache-control=[no-cache], connection=[close], content-type=[Flash], expires=[Sat, 19 May 2018 10:28:07 GMT], pragma=[no-cache], x-via=[1.1 PSlnlydxpi74:2 (Cdn Cache Server V2.0)[4 200 2]], x-ws-request-id=[5afffc37_PSlnlydxpi74_30876-48161]}
···

**Comment by rantianhua** [comment]
No response for a long time.

**Comment by Seachal** [comment]
对我来说， 第一个版本服务端没有对文件下载进行鉴权限制，可以正常下载，第二个版本，服务端开始改造增加鉴权，对已经调用过一次的下载链接进行失效处理，我这边就会遇到下面这样的异常， 
 ```
ava.net.SocketException: Connection failed with request[{Range=[bytes=4073926-8147851], User-Agent=[FileDownloader/1.7.7]}] response[{null=[HTTP/1.1 403 Forbidden], Access-Control-Allow-Methods=[GET], Access-Control-Allow-Origin=[*], Connection=[keep-alive], Content-Length=[238], Content-Type=[text/html], Date=[Mon, 29 Jan 2024 02:42:16 GMT], EagleId=[907b1f2217064961368347077e], Server=[Tengine], Timing-Allow-Origin=[*], Via=[cache14.cn1306[,0]], X-Android-Received-Millis=[1706496136376], X-Android-Response-Source=[NETWORK 403], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1706496136196]}] http-state[403] on task[-891346639-1], which is changed after verify connection, so please try again.   
```
最终发现是因为 下载库默认开启断点续传。
<img width="1058" alt="image" src="https://github.com/lingochamp/FileDownloader/assets/14776606/9e08f13e-211b-4e71-b8d3-70254f42e00d">


> Range 是一个请求首部，告知服务器返回文件的哪一部分。在一个 Range 首部中，可以一次性请求多个部分，服务器会以 multipart 文件的形式将其返回。如果服务器返回的是范围响应，需要使用 [206](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206) Partial Content 状态码。假如所请求的范围不合法，那么服务器会返回 [416](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/416) Range Not Satisfiable 状态码，表示客户端错误。服务器允许忽略 Range 首部，从而返回整个文件，状态码用 [200](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/200) 。

所以我这边的情况是，服务端做修改适配客户端的断点续传，客户端不需要修改。
