### ISSUE TITLE
如何实现断点下载

### ISSUE THREAD

**Issue by Boucles** [lingochamp/okdownload#69]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
默认就支持断点续传，如果后端支持`Range`并且`Etag`没有过期的情况下。

---

如果你下载的时候没有成功断点续传，请参看返回的`ResumeFailedCause`，如果通过`ResumeFailedCause`还无法确定，请直接查看日志内容。
