### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by zhangyanhbr** [lingochamp/okdownload#7]
当我用demo下载文件时,下载连接里面带有参数的时候(exp: url = xxxxx/thunt/get?t=f&id=c ),通过get 方法请求网络啊 ，能够正常连接上，但是下载回调里的文件总大小为0.结束时会跑抛出异常（exp: The current offset on block-info isn't update correct, 225508 != 0 on 0 ）。

**Comment by Jacksgong** [comment]
可否贴下，每个请求的请求头与响应头。

**Comment by zhangyanhbr** [comment]
你好，非常开心收到您的邮件，非常感谢，就是像这样的http://e-stg.ai.pingan.com.cn:81/thunt/ctxt/get?t=o&id=t_b5368235-fde2-4622-8ef9-fd22e07dc326 请求。看了一下，不是请求头的问题，文件是可以下载下来的，就是最后的处理的时候出现了问题。

**Comment by Jacksgong** [comment]
我猜测后端响应回来的内容大小为`0`，原本需要下载大小为`0bytes`的内容，但是最终接收到`225508bytes`大小的内容，导致最后报的这个错误。因此需要提供响应头。

**Comment by Jacksgong** [comment]
@zhangyanhbr 可否在最新的master上试试，我刚刚测试发现已经没有相关问题。
