### ISSUE TITLE
typo in wiki

### ISSUE THREAD

**Issue by LeadroyaL** [lingochamp/okdownload#70]
### OkDownload Version

v1.0.3

### Problem Describe

A typo in gradle dependence at the home page, as following:

[https://github.com/lingochamp/okdownload/wiki](https://github.com/lingochamp/okdownload/wiki)

> If you import component library it would be enabled by default, such as you import okhttp with implementation "com.liulishuo.okdownload.okhttp:1.0.1" on the gradle file, then okdownload will find it and enable okhttp as default for okdownload.

ATTENSION this string: > `"com.liulishuo.okdownload.okhttp:1.0.1"`

This should be: > `"com.liulishuo.okdownload:okhttp:1.0.1"`

The last period should be colon. This fucking typo wastes me half an hour.

**Comment by Jacksgong** [comment]
I'm so sorry，it's my fault, This typo is fixed now.
