### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by duncanokeyo** [lingochamp/okdownload#71]
could you implement downloading using jobscheduler provided by the android api...
https://developer.android.com/topic/performance/scheduling

**Comment by Jacksgong** [comment]
I have no idea about okdownload can relate to `JobScheduler` with performance? I can't get your point, could you please give me more detail about such things, or provide PR directly?

**Comment by Jacksgong** [comment]
I think okdownload no need `JobScheduler`, If you have any advanced advice, please tell me or please give PR it's very welcome, and this issue will be open again, thanks.
