### ISSUE TITLE
错误重试机制

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#74]
### OkDownload Version

v1.0.3

### Problem Describe

参照你这上面说的方法 https://github.com/lingochamp/okdownload/issues/15#issuecomment-380006418
我也尝试了重试，但是taskEnd的cause是**SAME_TASK_BUSY**
我的用法如下：
![image](https://user-images.githubusercontent.com/1260653/40341750-73a1f27e-5db9-11e8-802b-c71ab81b8f67.png)

**初始化的时候我已将重试次数设成0**

看了下调用顺序：
enqueue -> enqueueLocked -> inspectForConflict -> 
![image](https://user-images.githubusercontent.com/1260653/40342483-889890ee-5dbd-11e8-8a83-78a52ffa2973.png)
![image](https://user-images.githubusercontent.com/1260653/40342505-a4565c4e-5dbd-11e8-8bd5-7fc36a5220ae.png)
![image](https://user-images.githubusercontent.com/1260653/40342524-c256ea38-5dbd-11e8-8593-6c1577775ed5.png)
![image](https://user-images.githubusercontent.com/1260653/40342538-d34cfa26-5dbd-11e8-9428-2d6be86cd4c7.png)

**Comment by Jacksgong** [comment]
我一会儿给你看下，初步评估下来，确实这里`taskEnd`的时候，其实任务还在`Dispatcher`的队列中，所以再次`enqueue`的时候，回调了`SAME_TASK_BUSY`

**Comment by jaysowen** [comment]
OKDownload没有重试逻辑,确实有待商榷.关键是开发者自己想去实现也没有合理的回调逻辑机制

**Comment by rantianhua** [comment]
Please refer to #124
