### ISSUE TITLE
FileDownloadService默认是运行在独立进程，okdownload什么时候支持这个特性

### ISSUE THREAD

**Issue by lyf571321556** [lingochamp/okdownload#76]
### OkDownload Version
![image](https://user-images.githubusercontent.com/2295872/40459837-27b5cc18-5f36-11e8-9959-e23e45140df1.png)
![image](https://user-images.githubusercontent.com/2295872/40459841-2b6a626a-5f36-11e8-91d5-2f4c754aaf1d.png)

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by rantianhua** [comment]
OkDownload 不会再支持这个，实际上，在维护的过程中发现在库里面去做独立进程的事情不是一个正确的选择。首先会让很多设计变得复杂，实际性能也没有什么提高。而且 Android 8 开始对 Service 的限制越来越严格，这导致我们需要在下载库里面去处理 Android 的一些兼容性问题，实际很难处理而且一些问题无法处理，比如 https://github.com/lingochamp/FileDownloader/issues/1209 。

实际上，要不要使用单独进程下载应该完全交由使用者自己决定，当确定有这个需求的时候，依然可以在自己的独立进程去使用 OkDownload 。
