### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by duncanokeyo** [lingochamp/okdownload#78]
am experiencing alot of connection timeout especially when the internet is not stable.. is there a way i can set the connection timeout?

**Comment by sadlongit** [comment]
+1

**Comment by tranducthang1505** [comment]
+1

**Comment by alex-berdnikov** [comment]
+1

**Comment by hotsjf** [comment]
n+1

**Comment by oddshou** [comment]
+1

**Comment by Jacksgong** [comment]
Please check the doc from the [wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline), you can set a connectionFactory to OkDownload [like this](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component).

And the default Connection builder `DownloadUrlConnection.Factory` has been provided a way( with `Configuration`) to set its `readTimeout` and `connectTimeout` .

Furthermore, if you want to use okhttp3 please use `DownloadOkHttp3Connection.Factory` it also accepts `setBuilder` then you can do whatever you want.
