### ISSUE TITLE
First download for a resource, and kill the process within 1.5s after task is started, wrong complete status for the resource after process launch again

### ISSUE THREAD

**Issue by wufei608** [lingochamp/okdownload#82]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

在show each block progress 页面中，点击下载，然后App立刻被强制杀死，重新打开显示状态Completed,数据库中breakpoint表中没有任何信息，但是cache 文件夹下存在该下载文件，但确信的是该下载文件是不完整的。

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by CB2Git** [comment]
+1 目前的项目中遇到几率很大

**Comment by jaysowen** [comment]
我这边也是把代码fork了一份然后集成后发现有这个问题,开始了任务之后强杀,数据库没有断点的是数据

**Comment by CB2Git** [comment]
@Jacksgong ，目前我在几部手机上面分别进行了测试，对于华为手机，此问题重现几率较大，重现步骤，启动下载，log中可以查看到下载已经开始，然后强杀，再次启动会直接回调COMPLETED。相关log我会整理后发送到您的邮箱(igzhenjie@gmail.com)，请稍后查看

**Comment by Jacksgong** [comment]
@CB2Git ok，我晚上下班回去后一起看下。

**Comment by qq2748** [comment]
> 感谢反馈，该问题已经在 `1.0.4-SNAPSHOT` 上修复。 在发布 `1.0.4` 版本之前，可以参照[wiki](https://github.com/lingochamp/okdownload/wiki) 在snapshot版本上进行验证。

1.5版本, 任务队列下载 切换下载任务, 几率发生该错误
