### ISSUE TITLE
请问，request支持加入params么？

### ISSUE THREAD

**Issue by fly7632785** [lingochamp/okdownload#84]
你好，首先谢谢开源这个库，很nice.
其次，想问一下，request支持自定义么？
比如 method方式，或者 添加params

**Comment by Jacksgong** [comment]
谢谢。

1. method不支持定制（内部默认使用GET与HEAD(如果支持的话)），如果这块实在要定制，建议[直接定制Connection](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component)
2. params是支持的`DownloadTask#addHeader`

**Comment by fly7632785** [comment]
OK  3q 了解
