### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by duncanokeyo** [lingochamp/okdownload#86]
how  does okdownload handle a situation where i request a file to be downlaoded using 5 thread (or generally multipart download) but the server does not support multipart download... will the download fallback to using one thread?

**Comment by Jacksgong** [comment]
#### where i request a file to be downlaoded using 5 thread

You can feel free to use one of the following features to handle your request:

- The easiest way: `DownloadTask.Builder#setConnectionCount`, which has been written on the [wiki](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#vi-config-special-profile-for-task).
- The harder way, implement your own `DownloadStrategy` and overwrite `determineBlockCount` method, and provide your own `DownloadStrategy` to OkDownload through: `OkDownload.Builder`

#### but the server does not support multipart download... will the download fallback to using one thread?

If the backend doesn't support multipart download, okdownload will alter use one connection to download automatically, please feel free to use OkDownload, it will make sense.
