### ISSUE TITLE
开启下载 总是需要花费5-6秒的时间 是为什么？

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/okdownload#87]
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadManager: request start the task with url(http://apppic.3000test.com/s1/game_source_zip/4AC83676-AEC7-C6C7-1AA0-890210256F4F-1527837773.zip) path(/storage/emulated/0/Android/data/com.lzj.shanyi/files/game70987/70987resource.zip) isDirectory(FALSE)
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 320786811 file not suit, exists[FALSE], directory[FALSE]
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 320786811 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Connection=[Keep-Alive], Content-Length=[1], Content-Range=[bytes 0-0/150230835], Content-Type=[application/zip], Date=[Mon, 04 Jun 2018 08:20:12 GMT], ETag=["8f45733-56d8f7461011c"], Keep-Alive=[timeout=5, max=100], Last-Modified=[Fri, 01 Jun 2018 07:23:03 GMT], Server=[Apache/2.4.10 (Unix)], X-Android-Received-Millis=[1528100412426], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1528100412420]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: etag find "8f45733-56d8f7461011c" for task(320786811)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 320786811 file not suit, exists[FALSE], directory[FALSE]
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: fetch data with multiple connection(count: [5]) for task[320786811] totalLength[150230835]
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[0] range[0, 30046166) current offset(0)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[1] range[30046167, 60092333) current offset(30046167)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[2] range[60092334, 90138500) current offset(60092334)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[3] range[90138501, 120184667) current offset(90138501)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[4] range[120184668, -1) current offset(120184668)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=0-30046166], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=30046167-60092333], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=60092334-90138500], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=90138501-120184667], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=120184668-], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.428 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 486K, 17% free 3400K/4048K, paused 2ms, total 2ms
06-04 16:20:14.418 com.lzj.shanyi:filedownloader D/FileDownloader.RemitDatabase: sync cache to db 320786811
06-04 16:20:18.228 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 320786811 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Connection=[Keep-Alive], Content-Length=[30046167], Content-Range=[bytes 60092334-90138500/150230835], Content-Type=[application/zip], Date=[Mon, 04 Jun 2018 08:20:12 GMT], ETag=["8f45733-56d8f7461011c"], Keep-Alive=[timeout=5, max=100], Last-Modified=[Fri, 01 Jun 2018 07:23:03 GMT], Server=[Apache/2.4.10 (Unix)], X-Android-Received-Millis=[1528100418244], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1528100412439]}
06-04 16:20:18.228 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadRunnable: the connection[2] for 320786811, is connected range[60092334, 90138500) current offset[60092334] with code[206]
06-04 16:20:18.228 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: start fetch(2): range [60092334, 90138500), seek to[60092334]
06-04 16:20:18.238 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-04 16:20:18.238 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: handleProgress update model's status with progress
06-04 16:20:18.238 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
06-04 16:20:18.248 com.lzj.shanyi:filedownloader D/FileDownloader.FetchDataTask: require flushAndSync id[320786811] index[2] offset[60095174], consume[9]
06-04 16:20:18.538 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-04 16:20:18.538 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
06-04 16:20:18.838 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-04 16:20:18.838 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
06-04 16:20:19.138 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user
06-04 16:20:19.138 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: handleProgress notify user progress status
06-04 16:20:19.438 com.lzj.shanyi:filedownloader I/FileDownloader.DownloadStatusCallback: inspectNeedCallbackToUser need callback to user

**Comment by Jacksgong** [comment]
这个是FileDownloader的日志，请不要在okdownload这边提Task，谢谢。

---

根据日志:

```
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadManager: request start the task with url(http://apppic.3000test.com/s1/game_source_zip/4AC83676-AEC7-C6C7-1AA0-890210256F4F-1527837773.zip) path(/storage/emulated/0/Android/data/com.lzj.shanyi/files/game70987/70987resource.zip) isDirectory(FALSE)
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 320786811 file not suit, exists[FALSE], directory[FALSE]
06-04 16:20:12.398 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=0-0], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 320786811 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Connection=[Keep-Alive], Content-Length=[1], Content-Range=[bytes 0-0/150230835], Content-Type=[application/zip], Date=[Mon, 04 Jun 2018 08:20:12 GMT], ETag=["8f45733-56d8f7461011c"], Keep-Alive=[timeout=5, max=100], Last-Modified=[Fri, 01 Jun 2018 07:23:03 GMT], Server=[Apache/2.4.10 (Unix)], X-Android-Received-Millis=[1528100412426], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1528100412420]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: etag find "8f45733-56d8f7461011c" for task(320786811)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.FileDownloadUtils: can't continue 320786811 file not suit, exists[FALSE], directory[FALSE]
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: fetch data with multiple connection(count: [5]) for task[320786811] totalLength[150230835]
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[0] range[0, 30046166) current offset(0)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[1] range[30046167, 60092333) current offset(30046167)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[2] range[60092334, 90138500) current offset(60092334)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[3] range[90138501, 120184667) current offset(90138501)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.DownloadLaunchRunnable: enable multiple connection: id[320786811] index[4] range[120184668, -1) current offset(120184668)
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=0-30046166], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=30046167-60092333], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=60092334-90138500], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=90138501-120184667], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.418 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: <---- 320786811 request header {Range=[bytes=120184668-], User-Agent=[FileDownloader/1.7.4]}
06-04 16:20:12.428 com.lzj.shanyi:filedownloader D/dalvikvm: GC_FOR_ALLOC freed 486K, 17% free 3400K/4048K, paused 2ms, total 2ms
06-04 16:20:14.418 com.lzj.shanyi:filedownloader D/FileDownloader.RemitDatabase: sync cache to db 320786811
06-04 16:20:18.228 com.lzj.shanyi:filedownloader D/FileDownloader.ConnectTask: ----> 320786811 response header {null=[HTTP/1.1 206 Partial Content], Accept-Ranges=[bytes], Connection=[Keep-Alive], Content-Length=[30046167], Content-Range=[bytes 60092334-90138500/150230835], Content-Type=[application/zip], Date=[Mon, 04 Jun 2018 08:20:12 GMT], ETag=["8f45733-56d8f7461011c"], Keep-Alive=[timeout=5, max=100], Last-Modified=[Fri, 01 Jun 2018 07:23:03 GMT], Server=[Apache/2.4.10 (Unix)], X-Android-Received-Millis=[1528100418244], X-Android-Response-Source=[NETWORK 206], X-Android-Selected-Transport=[http/1.1], X-Android-Sent-Millis=[1528100412439]}
```

从日志可以很明显可以发现，从请求发出，到收到响应是近5s，这块的耗时，是网络以及后端处理的时间，与FileDownloader无关，请自行进行抓包进行处理。
