### ISSUE TITLE
队列下载不能指定文件名吗？

### ISSUE THREAD

**Issue by onlymash** [lingochamp/okdownload#88]
### OkDownload Version

v1.0.3

### Problem Describe
批量添加队列下载的时候好像没有指定文件名的选项

如图，窝有必须改文件名的理由。
这是单任务替换文件名里的 %20 为空格
```
        val fileName = url.substring(url.lastIndexOf("/") + 1).replace("%20", " ")
        val task = DownloadTask.Builder(url, dir)
                .setFilename(fileName)
                .setMinIntervalMillisCallbackProcess(30)
                .setPassIfAlreadyCompleted(false)
                .build()
```
多任务没有相关选项，自动获取的文件名没有替换 %20
![photo_2018-06-04_23-21-19](https://user-images.githubusercontent.com/5838634/40926141-11d61d5a-684e-11e8-9a9c-d263c7da2fe6.jpg)
![photo_2018-06-04_23-21-35](https://user-images.githubusercontent.com/5838634/40926144-12589456-684e-11e8-9256-6819ba4e1e01.jpg)

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by onlymash** [comment]
看了源码 大概明白了
```
public Builder(QueueSet set) {
            this(set, new ArrayList<DownloadTask>());
        }

        public Builder(QueueSet set, ArrayList<DownloadTask> taskArrayList) {
            this.set = set;
            this.boundTaskList = taskArrayList;
        }
```
Sample 的示例用了第一个，用第二个就能给每个任务定义文件名了

**Comment by mattxzhang** [comment]
@onlymash 能发下你的demo么？

**Comment by onlymash** [comment]
@mattxzhang https://github.com/onlymash/moebooru-android
