### ISSUE TITLE
我用的通知栏下载那个demo，下载过程中一直有消息提示声音

### ISSUE THREAD

**Issue by DaveBoy** [lingochamp/okdownload#92]
### OkDownload Version

v1.0.3

### Problem Describe

下载过程中一直有消息提示声音

### Log

D/OpenGLRenderer:   HWUI Binary is  enabled
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/OpenGLRenderer:   HWUI Binary is  enabled
W/InputMethodManager: startInputReason = 1
V/AudioManager: playSoundEffect   effectType: 0
D/NotificationActivity: taskStart
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
D/NotificationActivity: infoReady id[1] url[https://cdn.llscdn.com/yy/files/tkzpx40x-lls-LLS-5.7-785-20171108-111118.apk] etag["lqpdGNkXwrNeqtOTudN3FoWVrFPF"] taskOnlyProvidedParentPath[false] parent path[/storage/emulated/0/Android/data/com.cqut.jwoa.moa/cache] filename[notification-file.apk] block(s):[[0, 14474937)-current:0, [14474938, 28949873)-current:0, [28949874, 43424809)-current:0] false
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
D/NotificationActivity: progress 4096
E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}

**Comment by DaveBoy** [comment]
ipad aht-al09

**Comment by kslr** [comment]
调低级别
