### ISSUE TITLE
动态添加下载url

### ISSUE THREAD

**Issue by zhijianfree** [lingochamp/okdownload#94]
你好，我现在感觉在使用okdownload的时候，在动态添加下载文件时候遇到问题，比如下载文件错乱。我尝试过使用多个DownloadContex来下载，但是也不行。 最后尝试用下面的toBuilder(),也不行

![111](https://user-images.githubusercontent.com/21210211/41098821-404d7898-6a8f-11e8-955c-1d9b5191be49.png)

**Comment by Jacksgong** [comment]
#### 下载文件错乱

可否具体点吗？我们内部也在大量使用没有遇到过类似问题，并且OkDownload中有严格的机制保障不会有多个任务对同一个文件进行写入。

---

最后我不是很清楚你的具体问题什么？

**Comment by rantianhua** [comment]
No response for a long time.
