### ISSUE TITLE
如何让它支持https

### ISSUE THREAD

**Issue by contribute1986** [lingochamp/okdownload#96]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:...

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
```

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

**Comment by Jacksgong** [comment]
默认的`DownloadConnection`采用的是`UrlConnection`，如果是HTTPS协议，自动会采用`HttpsUrlConnection`，本身就支持，不需要特殊适配。
