### ISSUE TITLE
1.0.4大概什么时候可以发布？

### ISSUE THREAD

**Issue by kerneltea** [lingochamp/okdownload#97]
请问1.0.4之前不是发布了嘛，现在又辙回了？
1.0.4大概什么时候可以发布？

**Comment by Jacksgong** [comment]
1. 1.0.4从来没有Release过
2. 如果你着急希望用到1.0.4的特性以及修改，请直接根据[Wiki](https://github.com/lingochamp/okdownload/wiki)引入 `1.0.4-snapshot`版本即可
3. 发布时间暂不确定，如果发现1.0.3中有什么问题，欢迎PR，我们会跟进到`1.0.4-snapshot`中
