### ISSUE TITLE
okdownload 项目 导入Android studio 报错

### ISSUE THREAD

**Issue by corabsins** [lingochamp/okdownload#98]
### OkDownload Version

v1.0.2-SNAPSHOT

### Problem Describe
导入后 同步完成报错，错误如下：
Error:Cannot invoke method dependsOn() on null object
请问下这个是什么原因？

**Comment by Jacksgong** [comment]
具体堆栈?

**Comment by corabsins** [comment]
2018/6/20
19:30	Gradle sync started

19:30	Gradle sync failed: Cannot invoke method dependsOn() on null object
			Consult IDE log for more details (Help | Show Log) (3s 284ms)

19:30	Invalid VCS root mapping
			The directory D:\corabsins\code\okdownload-master is registered as a Git root, but no Git repositories were found there.
			Configure

19:30	Invalid VCS root mapping
			The directory D:\corabsins\code\okdownload-master is registered as a Git root, but no Git repositories were found there.
			Configure

19:30	Error Loading Project: Cannot load 9 modules Details...

报的这个 错

**Comment by mrqatom** [comment]
我也遇到了，是codecov.gradle文件中tasks.findByName('okcheckDebug')这句话报错了
在你们插件里没有定义/或没找到okcheckDebug这个task，所以dependsOn空指针

**Comment by Jacksgong** [comment]
挺奇怪的，@mrqatom 与 @corabsins 的报错信息似乎对的上。不过我们有使用[okcheck](https://github.com/lingochamp/okcheck)，并且[travis](https://github.com/lingochamp/okdownload/blob/master/.travis.yml)跑的都是`okcheckDebug`，这个也是为了在跑`okcheckDebug`时候把覆盖率计算跑了。

**Comment by mrqatom** [comment]
是不是因为没有依赖到？如果题主不需要计算单元测试的覆盖率，把那句话注释掉就可以编译了

**Comment by Jacksgong** [comment]
我修改下策略吧。

**Comment by corabsins** [comment]
git的问题可以解决，Error:Read timed out 的问题不知道是什么原因

**Comment by corabsins** [comment]
18:29	Invalid VCS root mapping
			The directory D:\corabsins\code\okdownload-master is registered as a Git root, but no Git repositories were found there.
			Configure

18:31	Gradle sync failed: Read timed out
			Consult IDE log for more details (Help | Show Log) (1m 36s 330ms)
