### ISSUE TITLE
v1.0.3 ProGuard 异常 

### ISSUE THREAD

**Issue by XieEDeHeiShou** [lingochamp/okdownload#99]
DownloadContext 引用了 SuppressFBWarnings 
 注解, 但 Sample 中并没有 -dontwarn 该类. 

https://github.com/lingochamp/okdownload/blob/master/okdownload/src/main/java/com/liulishuo/okdownload/DownloadContext.java#L43

https://github.com/lingochamp/okdownload/blob/master/okdownload/build.gradle#L33

https://github.com/lingochamp/okdownload/blob/master/sample/proguard-rules.pro#L28-L47

**Comment by liangchenhe55** [comment]
add 
```
-dontwarn edu.umd.cs.findbugs.annotations.SuppressFBWarnings
```

**Comment by rantianhua** [comment]
@XieEDeHeiShou 我刚刚在 Demo 中用 `./gradlew assembleRelease` 试了一下，没有发现混淆中出现什么异常，请问你是怎么出现这个问题的？
